Repository google/flax, pull requests merged in 2020-09, with the labels that each got.

#433 add scope aliasing to lift.pack
  flax/core/lift.py
  flax/core/scope.py
  flax/core/tests/lift_test.py
Labels: cla: yes

#343 ResNet v1 is missing ReLU in root-block
  examples/imagenet/models.py
Labels: cla: yes

#441 Update attention layers with simpler flat forms, update wmt example.
  flax/linen/__init__.py
  flax/linen/attention.py
  linen_examples/wmt/decode.py
  linen_examples/wmt/models.py
  linen_examples/wmt/train.py
  tests/linen/linen_attention_test.py
Labels: cla: yes

#446 Hook up previously ignored n_logistic_mix FLAG in PixelCNN++
  examples/pixelcnn/train.py
  linen_examples/pixelcnn/pixelcnn.py
  linen_examples/pixelcnn/train.py
Labels: cla: yes

#436 Improves error message for naming modules in setup()
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#450 Renames get_param to get_initial_params in seq2seq and mnist Linen examples
  linen_examples/mnist/mnist_lib.py
  linen_examples/seq2seq/train.py
  linen_examples/seq2seq/train_test.py
Labels: cla: yes

#444 Add single input conv and conv_transpose support
  flax/nn/linear.py
  tests/nn_linear_test.py
Labels: cla: yes

#451 unify variable_in_axes and variable_out_axes
  flax/core/lift.py
  flax/core/tests/lift_test.py
  linen_examples/core_design_test/attention_simple.py
  linen_examples/core_design_test/big_resnets.py
  linen_examples/core_design_test/scan.py
  linen_examples/core_design_test/vmap.py
  linen_examples/linen_design_test/attention_simple.py
  linen_examples/seq2seq/train.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes

#453 Exposing more Conv flags from ConvLSTM.
  flax/nn/recurrent.py
Labels: cla: yes

#456 Fix frozen dict
  flax/core/frozen_dict.py
  flax/core/lift.py
  tests/core/frozen_dict_test.py
  tests/core/lift_test.py
  tests/core/scope_test.py
Labels: cla: yes

#460 Add Linen alpha README
  flax/linen/README.md
Labels: cla: yes

#419 Add unittest for LM1B example.
  examples/lm1b/train.py
  examples/lm1b/train_test.py
  pytest.ini
Labels: cla: yes

#461 replace kinds with collections
  flax/core/__init__.py
  flax/core/flax_functional_engine.ipynb
  flax/core/lift.py
  flax/core/scope.py
  flax/linen/module.py
  linen_examples/core_design_test/attention_simple.py
  linen_examples/core_design_test/big_resnets.py
  linen_examples/core_design_test/resnet.py
  linen_examples/core_design_test/scan.py
  linen_examples/core_design_test/tied_autoencoder.py
  linen_examples/core_design_test/vmap.py
  linen_examples/core_design_test/weight_std.py
  linen_examples/imagenet/train.py
  linen_examples/linen_design_test/attention_simple.py
  linen_examples/linen_design_test/autoencoder.py
  linen_examples/linen_design_test/linear_regression.py
  linen_examples/linen_design_test/mlp_explicit.py
  linen_examples/linen_design_test/mlp_inline.py
  linen_examples/linen_design_test/mlp_lazy.py
  linen_examples/linen_design_test/tied_autoencoder.py
  linen_examples/linen_design_test/weight_std.py
  linen_examples/mnist/mnist_lib.py
  linen_examples/mnist/mnist_lib_test.py
  linen_examples/pixelcnn/model_test.py
  linen_examples/pixelcnn/sample.py
  linen_examples/pixelcnn/train.py
  linen_examples/seq2seq/train.py
  linen_examples/vae/train.py
  linen_examples/wmt/train.py
  tests/core/scope_test.py
  tests/linen/linen_attention_test.py
  tests/linen/linen_linear_test.py
  tests/linen/linen_test.py
  tests/linen/linen_transforms_test.py
  tests/linen/module_test.py
  tests/linen/toplevel_test.py
  tests/nn_test.py
Labels: cla: yes

#469 Add linen intro notebook
  docs/notebooks/linen_intro.ipynb
  flax/linen/README.md
Labels: cla: yes

#471 force upgrade pygments
  docs/requirements.txt
Labels: cla: yes

#468 Remove unnecessary shared() from seq2seq example
  examples/seq2seq/train.py
  howtos/diffs/scheduled-sampling.diff
Labels: cla: yes

#474 Fix scan broadcast issue
  docs/notebooks/linen_intro.ipynb
  flax/core/flax_functional_engine.ipynb
  flax/core/lift.py
  flax/core/unified_transforms.py
  flax/linen/__init__.py
  flax/linen/transforms.py
  linen_examples/core_design_test/scan.py
  linen_examples/seq2seq/train.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes

#475 Expose __version__ attribute
  flax/__init__.py
  flax/version.py
  setup.py
Labels: cla: yes

#463 Use ConfigDict to represent hyperparameter configurations for MNIST example
  howtos/README.md
  howtos/diffs/checkpointing.diff
  howtos/diffs/distributed-training.diff
  howtos/diffs/ensembling.diff
  howtos/diffs/polyak-averaging.diff
  setup.py
Labels: cla: yes

#487 Update HOWTOs HOWTO for 3way merge
  docs/howtos/howtos-howto.md
Labels: cla: yes

#492 Add configdict for mnist linen example to configure HP.
  linen_examples/mnist/README.md
  linen_examples/mnist/configs/default.py
  linen_examples/mnist/mnist_lib.py
  linen_examples/mnist/mnist_lib_test.py
  linen_examples/mnist/mnist_main.py
Labels: cla: yes

#488 Make Linen intro Colab link open in Colab
  flax/linen/README.md
Labels: cla: yes

#476 Update version number in version.py (edit: Update version number in setup.py)
  flax/version.py
Labels: Status: review needed, cla: yes

#481 core docstrings
  flax/core/axes_scan.py
  flax/core/lift.py
  flax/core/scope.py
Labels: Status: review needed, cla: yes

#473 Improves HOWTO docs.
  docs/howtos/howtos-howto.md
  howtos/README.md
Labels: Priority: low - P3, cla: yes

#499 design unit tests
  linen_examples/core_design_test/auto_encoder.py
  linen_examples/core_design_test/batch_norm.py
  linen_examples/core_design_test/custom_vjp.py
  linen_examples/core_design_test/mlp.py
  linen_examples/core_design_test/resnet.py
  linen_examples/core_design_test/scan.py
  linen_examples/core_design_test/transformer.py
  linen_examples/core_design_test/vmap.py
  tests/core/design/core_attention_test.py
  tests/core/design/core_auto_encoder_test.py
  tests/core/design/core_big_resnets_test.py
  tests/core/design/core_custom_vjp_test.py
  tests/core/design/core_dense_test.py
  tests/core/design/core_flow_test.py
  tests/core/design/core_resnet_test.py
  tests/core/design/core_scan_test.py
  tests/core/design/core_tied_autoencoder_test.py
  tests/core/design/core_vmap_test.py
  tests/core/design/core_weight_std_test.py
Labels: cla: yes

#500 Refactor linen Imagenet Example.
  linen_examples/imagenet/README.md
  linen_examples/imagenet/configs/default.py
  linen_examples/imagenet/configs/fake_data_benchmark.py
  linen_examples/imagenet/configs/v100_x8.py
  linen_examples/imagenet/configs/v100_x8_mixed_precision.py
  linen_examples/imagenet/imagenet_benchmark.py
  linen_examples/imagenet/imagenet_fake_data_benchmark.py
  linen_examples/imagenet/imagenet_lib.py
  linen_examples/imagenet/imagenet_lib_test.py
  linen_examples/imagenet/imagenet_main.py
  linen_examples/imagenet/input_pipeline.py
  linen_examples/imagenet/models.py
  linen_examples/imagenet/models_test.py
  linen_examples/imagenet/train_fake_data_benchmark.py
Labels: Status: review needed, cla: yes

#491 Migrating ConvLSTM from Flax to Linen
  flax/linen/__init__.py
  flax/linen/recurrent.py
  tests/linen/linen_test.py
Labels: cla: yes
