Repository google/flax, pull requests merged in 2020-11, with the labels that each got.

#578 improved Embed input type check
  flax/linen/linear.py
  flax/nn/linear.py
Labels: cla: yes

#586 add numpy scalar serialization
  flax/serialization.py
  tests/serialization_test.py
Labels: cla: yes

#577 Add the silu activation function
  flax/core/nn/__init__.py
  flax/linen/__init__.py
  flax/linen/activation.py
  flax/nn/__init__.py
  flax/nn/activation.py
Labels: cla: yes

#564 Linen Conv and ConvTranspose support batch free input
  flax/linen/linear.py
  tests/linen/linen_linear_test.py
Labels: cla: yes

#551 kernel_size parameter can be an int for 1d Conv and ConvTranspose
  flax/linen/linear.py
  flax/nn/linear.py
  tests/linen/linen_linear_test.py
  tests/nn_linear_test.py
Labels: cla: yes

#563 Allow restoring raw state_dict using checkpoints.restore_checkpoint().
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: cla: yes

#550 Update README.md: point feature requests to discussions
  README.md
Labels: cla: yes

#590 Remove non hashable static args
  examples/lm1b/Colab_Language_Model.ipynb
  examples/lm1b/train.py
  examples/nlp_seq/train.py
  examples/sst2/model.py
  examples/wmt/train.py
  flax/core/scope.py
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#596 Add pretty printing for FrozenDict
  flax/core/frozen_dict.py
  tests/core/frozen_dict_test.py
Labels: cla: yes

#542 Creating getting started notebooks for JAX + Flax basics
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/jax_for_the_impatient.ipynb
Labels: cla: yes

#599 Fix incorrect reference to DeprecationWarning
  flax/training/prefetch_iterator.py
Labels: cla: yes

#608 Update linen intro notebook for new mutated collection behavior of apply.
  docs/notebooks/linen_intro.ipynb
Labels: cla: yes

#597 Add __repr__ to linen module
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#600 Adds two missing absltest.main()
  tests/linen/linen_test.py
  tests/linen/toplevel_test.py
Labels: Priority: P3 - low, cla: yes

#622 Update setup.py
  setup.py
Labels: cla: yes

#624 Update setup.py
  setup.py
Labels: cla: yes

#609 nlp_seq to linen port
  examples/nlp_seq/models.py
  examples/nlp_seq/train.py
Labels: cla: yes

#602 Adds more docstrings to functional core
  flax/core/scope.py
Labels: cla: yes

#628 Raise minimal version to 0.1.77
  setup.py
Labels: cla: yes

#626 Changes due to review of andsteing no resolved PR #609
  examples/nlp_seq/models.py
  examples/nlp_seq/train.py
Labels: Priority: P1 - high, Status: in progress, Type: example, cla: yes

#625 Adds Module docstrings and updates readthedocs
  docs/conf.py
  docs/flax.linen.rst
  flax/core/scope.py
  flax/core/variables.py
  flax/linen/__init__.py
  flax/linen/module.py
  tests/linen/module_test.py
Labels: Priority: P1 - high, Status: in progress, cla: yes

#640 Tiny rtd fixes
  flax/linen/module.py
Labels: cla: yes

#588 Updates top-level doc-string of functional core Scopes
  flax/core/scope.py
Labels: cla: yes

#653 Relax limit on calling methods on unbound modules
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#666 Fixed typos and missing attribute in module docstrings.
  flax/linen/linear.py
Labels: cla: yes

#664 Minor linting - Flax basics
  docs/notebooks/flax_basics.ipynb
Labels: cla: yes

#655 Improve frozendict performance
  flax/core/frozen_dict.py
Labels: cla: yes

#662 Add the centered version of RMSProp
  flax/optim/rmsprop.py
  tests/optim_test.py
Labels: cla: yes

#671 Improves imagenet examples file structure
  linen_examples/imagenet/README.md
  linen_examples/imagenet/configs/default.py
  linen_examples/imagenet/imagenet_benchmark.py
  linen_examples/imagenet/imagenet_fake_data_benchmark.py
  linen_examples/imagenet/main.py
  linen_examples/imagenet/models_test.py
  linen_examples/imagenet/requirements.txt
  linen_examples/imagenet/train.py
  linen_examples/imagenet/train_test.py
Labels: cla: yes

#632 added README.md to optim folder
  flax/optim/README.md
Labels: cla: yes

#675 run pytype for linen examples
  linen_examples/imagenet/imagenet_fake_data_benchmark.py
  tests/run_all_tests.sh
Labels: Priority: P2 - medium, Status: in progress, Type: enhancement, cla: yes
