Repository google/flax, pull requests merged in 2020-03, with the labels that each got.

#27 Minor fixes to the flax_intro notebook
  README.md
  docs/notebooks/flax_intro.ipynb
  flax/nn/recurrent.py
Labels: cla: yes

#18 Fixed LSTMCell bias initialisation
  flax/nn/recurrent.py
  tests/nn_test.py
Labels: cla: yes

#30 Add __hash__ implementation of Model
  flax/nn/base.py
Labels: cla: yes

#31 Fix tests in seq2seq
  examples/seq2seq/train_test.py
Labels: cla: yes

#25 Ensure shared modules appear in params only once.
  flax/nn/base.py
  tests/nn_test.py
Labels: cla: yes

#8 minor spelling tweaks
  docs/philosophy.md
  examples/lm1b/models.py
  flax/nn/attention.py
  flax/nn/base.py
  flax/nn/pooling.py
  flax/nn/recurrent.py
  flax/nn/stochastic.py
  flax/optim.py
  flax/struct.py
  flax/training/prefetch_iterator.py
  flax/traverse_util.py
Labels: cla: yes

#29 Fix mime type of description in setup.py
  setup.py
Labels: cla: yes

#32 Add fast sampling to lm1b example, checkpointing, bugfixes.
  examples/lm1b/decode.py
  examples/lm1b/dynamic_batching.py
  examples/lm1b/dynamic_batching_test.py
  examples/lm1b/input_pipeline.py
  examples/lm1b/models.py
  examples/lm1b/train.py
Labels: cla: yes

#40 Modify MNIST code in docs to do dtype conversion for TPUs.
  README.md
  docs/annotated_mnist.md
Labels: cla: yes

#46 Add docs build to travis
  .travis.yml
Labels: cla: yes

#34 Fix collection anchor
  flax/nn/base.py
  tests/nn_test.py
Labels: cla: yes

#44 Add create howtos script
  .github/workflows/apply-howto-branches.yml
  howtos/README.md
  howtos/diffs/howto-ensembling.diff
  howtos/scripts/apply_howto_diffs.sh
  howtos/scripts/pack_howto_diffs.sh
Labels: cla: yes

#48 add linterrc
  pylintrc
Labels: cla: yes

#47 Updated README.md
  README.md
Labels: cla: yes

#51 Setup a bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes

#52 Setup a bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes

#56 Add bug label to the bug issue template.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes

#41 Subsume '_' into the prefix kwarg of {save,restore}_checkpoint.
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: cla: yes

#55 Remove replicate and optimize calls from examples
  README.md
  docs/annotated_mnist.md
  examples/cifar10/train.py
  examples/graph/train.py
  examples/lm1b/train.py
  examples/mnist/train.py
  examples/nlp_seq/train.py
  examples/seq2seq/train.py
  flax/optim.py
Labels: cla: yes

#59 Moves HOWTOs to readthedocs
  docs/howtos.md
  docs/index.rst
  howtos/README.md
Labels: cla: yes

#57 Add the Flax FAQs and the annotated MNIST example notebook.
  docs/faq.md
  docs/index.rst
  docs/notebooks/annotated_mnist_example.ipynb
Labels: cla: yes

#58 Update lstm example
  examples/seq2seq/train.py
Labels: cla: yes

#60 Add a public TPU-enabled colab version of the LM1B language model.
  examples/lm1b/Colab_Language_Model.ipynb
Labels: cla: yes

#63 Deprecate `create` and `create_by_shape` and replace them with `init` and `init_by_shape`
  README.md
  docs/annotated_mnist.md
  docs/faq.md
  docs/notebooks/annotated_mnist_example.ipynb
  docs/notebooks/flax_intro.ipynb
  examples/cifar10/train.py
  examples/graph/train.py
  examples/graph/train_test.py
  examples/imagenet/train.py
  examples/lm1b/train.py
  examples/mnist/train.py
  examples/nlp_seq/train.py
  examples/seq2seq/train.py
  examples/wip/moco/train_moco.py
  flax/jax_utils.py
  flax/nn/base.py
  flax/nn/recurrent.py
  tests/nn_attention_test.py
  tests/nn_linear_test.py
  tests/nn_test.py
  tests/serialization_test.py
Labels: cla: yes

#64 Rename SelfAttention to MultiHeadDotProductAttention.
  flax/nn/__init__.py
  flax/nn/attention.py
  tests/nn_attention_test.py
Labels: cla: yes

#66 Adds Polyak averaging HOWTO
  docs/howtos.md
  howtos/diffs/howto-polyak-averaging.diff
Labels: cla: yes

#67 Temporarily disable the non-compiling annotated MNIST example.
  docs/notebooks/annotated_mnist_example._ipynb
Labels: cla: yes

#68 Adds HOWTO for distributed training
  docs/howtos.md
  howtos/diffs/howto-distributed-training.diff
Labels: cla: yes

#71 Add steps per second metric to imagenet example.
  examples/imagenet/train.py
Labels: cla: yes

#65 move scan_in_dim to jax_utils
  examples/seq2seq/train.py
  flax/jax_utils.py
  flax/nn/attention.py
  tests/nn_attention_test.py
Labels: cla: yes, refactor

#73 README improvements towards 0.1
  README.md
Labels: cla: yes

#49 Stateful check
  flax/nn/base.py
  flax/nn/utils.py
  tests/nn_test.py
Labels: cla: yes

#75 fix seq2seq example, fix batch_metrics to metrics
  examples/seq2seq/train.py
Labels: cla: yes

#80 Add some newlines
  docs/notebooks/annotated_mnist_example._ipynb
  docs/notebooks/flax_intro.ipynb
  examples/lm1b/Colab_Language_Model.ipynb
Labels: cla: yes

#76 Fix deprecated api usage
  examples/cifar10/train.py
  examples/imagenet/train.py
  examples/lm1b/Colab_Language_Model.ipynb
  flax/jax_utils.py
  flax/optim.py
  flax/training/common_utils.py
  howtos/diffs/howto-distributed-training.diff
  howtos/scripts/pack_howto_diffs.sh
  tests/nn_attention_test.py
  tests/nn_test.py
  tests/optim_test.py
Labels: cla: yes, enhancement, refactor

#77 add hash based paramter rngs
  flax/nn/base.py
  tests/nn_test.py
Labels: bug, cla: yes

#83 Create pythonpublish.yml
  .github/workflows/pythonpublish.yml
Labels: cla: yes

#87 Fix missing imports in example
  docs/annotated_mnist.md
Labels: cla: yes

#88 Avoid trying to load temporary checkpoint in `training.checkpoints.restore_checkpoint`.
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: cla: yes

#89 Save unreplicated optimizer in lm1b example.
  examples/lm1b/train.py
Labels: cla: yes

#92 Add flax.nn.module to online docs
  docs/flax.nn.rst
Labels: cla: yes

#82 update setup for pypi wheel
  .gitignore
  flax/training/__init__.py
  requirements.txt
  setup.py
Labels: cla: yes

#85 Remove use of nn.stochastic from seq2seq example
  examples/seq2seq/train.py
  examples/seq2seq/train_test.py
Labels: cla: yes

#79 added readme.md and updated documentation in train
  examples/nlp_seq/README.md
  examples/nlp_seq/models.py
  examples/nlp_seq/train.py
Labels: cla: yes, documentation, example

#90 Make decoding jittable.
  examples/seq2seq/train.py
Labels: cla: yes, enhancement, example

#9 Examples/vae
  examples/vae/README.md
  examples/vae/example.png
  examples/vae/main.py
  examples/vae/requirements.txt
  examples/vae/results/.gitignore
  examples/vae/utils.py
Labels: cla: yes, example

#96 Restructure RTD landing page
  docs/index.rst
  docs/notebooks/flax_guided_tour.ipynb
Labels: cla: yes

#98 Add README.md to examples
  examples/graph/README.md
  examples/graph/train.py
  examples/imagenet/README.md
  examples/imagenet/input_pipeline.py
  examples/imagenet/train.py
  examples/lm1b/README.md
  examples/mnist/README.md
  examples/nlp_seq/README.md
  examples/nlp_seq/train.py
  examples/requirements.txt
  examples/seq2seq/README.md
  examples/seq2seq/train.py
Labels: cla: yes, documentation, example

#93 add flatten dict utilities
  flax/optim.py
  flax/traverse_util.py
  tests/traverse_util_test.py
Labels: cla: yes

#103 Improve FAQ
  docs/faq.md
Labels: cla: yes

#110 Fix lm1b colab to request recent nightly tpu backend.
  examples/lm1b/Colab_Language_Model.ipynb
Labels: cla: yes

#107 Fix #101
  examples/vae/main.py
Labels: cla: yes

#100 Improve HOWTOs
  .travis.yml
  docs/.gitignore
  docs/Makefile
  docs/format_howtos.py
  docs/howtos-howto.md
  docs/howtos.rst
  howtos/diffs/howto-distributed-training.diff
  howtos/diffs/howto-ensembling.diff
  howtos/scripts/pack_howto_diffs.sh
Labels: cla: yes

#113 Add egg-info to .gitignore
  .gitignore
Labels: cla: yes

#115 Include output from format_howtos.py in git
  docs/.gitignore
  docs/_formatted_howtos/howto-distributed-training.diff.html
  docs/_formatted_howtos/howto-ensembling.diff.html
  docs/_formatted_howtos/howto-polyak-averaging.diff.html
Labels: cla: yes

#116 Bring back the correct ensembling HOWTO
  docs/_formatted_howtos/howto-ensembling.diff.html
  howtos/diffs/howto-ensembling.diff
  howtos/scripts/pack_howto_diffs.sh
Labels: cla: yes

#117 Shorten, simplify and clarify the ensembling HOWTO
  docs/_formatted_howtos/howto-ensembling.diff.html
  howtos/diffs/howto-ensembling.diff
Labels: cla: yes

#119 Tiny tweaks to comments in lm1b example.
  examples/lm1b/README.md
  examples/lm1b/decode.py
  examples/lm1b/input_pipeline.py
  examples/lm1b/train.py
Labels: cla: yes

#106 Add support for loading checkpoint at a specific step.
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: cla: yes

#118 Build HOWTO HTML snippets during docs build time.
  .travis.yml
  docs/.gitignore
  docs/Makefile
  docs/_formatted_howtos/howto-distributed-training.diff.html
  docs/_formatted_howtos/howto-ensembling.diff.html
  docs/_formatted_howtos/howto-polyak-averaging.diff.html
  docs/conf.py
Labels: cla: yes

#126 Change "howto-" prefix to "howto/"
  howtos/diffs/distributed-training.diff
  howtos/diffs/ensembling.diff
  howtos/diffs/polyak-averaging.diff
  howtos/scripts/apply_howto_diffs.sh
  howtos/scripts/pack_howto_diffs.sh
Labels: cla: yes

#124 factor out testing script
  .travis.yml
  tests/run_all_tests.sh
Labels: cla: yes

#125 add stochastic check
  flax/nn/stochastic.py
  flax/nn/utils.py
  tests/nn_test.py
Labels: cla: yes

#81 Add a vscode container dev setup
  dev/.devcontainer/Dockerfile
  dev/.devcontainer/devcontainer.json
  dev/README.md
Labels: cla: yes

#135 Fix an error message -> the f of the f-string was missing.
  flax/nn/base.py
Labels: cla: yes

#134 Added out_features parameter on the last projection layer of MultiHeadAttention
  flax/nn/attention.py
Labels: cla: yes

#132 Fix HOWTO rendering and links to GitHub
  docs/format_howtos.py
  docs/howtos.rst
Labels: cla: yes

#128 Fix incorrect variable in apply_howto_diffs.sh
  howtos/scripts/apply_howto_diffs.sh
Labels: cla: yes

#130 README changes
  README.md
Labels: cla: yes

#139 Make format_docs.py less sensitive to pygments output
  docs/format_howtos.py
Labels: cla: yes

#127 Add test requirements
  setup.py
  tests/run_all_tests.sh
Labels: cla: yes

#121 Update CIFAR10 example
  examples/cifar10/README.md
  examples/cifar10/input_pipeline.py
  examples/cifar10/models/pyramidnet.py
  examples/cifar10/models/utils.py
  examples/cifar10/models/wideresnet.py
  examples/cifar10/models/wideresnet_shakeshake.py
  examples/cifar10/train.py
  examples/nlp_seq/README.md
Labels: cla: yes, example

#108 Add LAMB optimizer
  flax/optim.py
Labels: cla: yes

#120 Add readme to examples
  examples/README.md
Labels: cla: yes, example

#137 Avoid singleton dimensions in batchnorm params
  flax/nn/normalization.py
Labels: cla: yes

#140 Add new lines in the CIFAR10 README
  examples/cifar10/README.md
Labels: cla: yes

#145 run_all_tests.sh should die on failure.
  tests/nn_test.py
  tests/run_all_tests.sh
Labels: cla: yes

#147 Closes #129: reorganize optim into directory structure
  flax/optim/__init__.py
  flax/optim/adam.py
  flax/optim/base.py
  flax/optim/lamb.py
  flax/optim/lars.py
  flax/optim/momentum.py
  flax/optim/sgd.py
  flax/optim/weight_norm.py
  tests/optim_test.py
Labels: cla: yes

#141 Add ConvTranspose Module
  CHANGELOG.md
  flax/nn/__init__.py
  flax/nn/linear.py
  tests/nn_linear_test.py
Labels: cla: yes, enhancement

#111 Support variable length sequences in Seq2Seq example.
  examples/seq2seq/train.py
  examples/seq2seq/train_test.py
  flax/nn/base.py
Labels: cla: yes

#146 Use better default names for Module tree.
  CHANGELOG.md
  flax/nn/base.py
Labels: cla: yes

#151 remove jaxlib dependency
  setup.py
Labels: cla: yes

#152 change required python version in README
  README.md
Labels: cla: yes

#150 fix setup failure due to non-ascii characters
  setup.py
Labels: cla: yes
