Repository google/flax, pull requests merged in 2020-04, with the labels that each got.

#154 Fix bad path in howtos howto.
  docs/howtos-howto.md
Labels: cla: yes

#158 Update README.md
  README.md
Labels: cla: yes

#155 Use '_rng' for init rng arg to allow apply to have an 'rng' arg.
  flax/nn/base.py
Labels: cla: yes

#153 Fix lint errors and missing rngs in Seq2Seq example.
  examples/seq2seq/train.py
  examples/seq2seq/train_test.py
Labels: cla: yes

#143 Fix vae
  examples/vae/README.md
  examples/vae/example.png
  examples/vae/main.py
  examples/vae/reconstruction.png
  examples/vae/results/.gitignore
  examples/vae/sample.png
  examples/vae/train.py
Labels: bug, cla: yes, enhancement, example

#159 lift stochastic scope in init_by_shape
  flax/nn/base.py
  tests/nn_test.py
Labels: cla: yes

#149 Add SST-2 NLP example.
  examples/sst2/README.md
  examples/sst2/input_pipeline.py
  examples/sst2/model.py
  examples/sst2/train.py
Labels: cla: yes

#142 Fix ImageNet example readme
  examples/imagenet/README.md
Labels: cla: yes, enhancement, example

#164 Fix setups table in README
  examples/sst2/README.md
Labels: cla: yes

#165 Link to SST-2 example from README
  README.md
Labels: cla: yes

#170 Use github actions for continuous integration
  .github/workflows/build.yml
  .travis.yml
Labels: cla: yes

#162 Minor fix-up to ConvTranspose
  flax/nn/linear.py
Labels: cla: yes

#167 DOC: removed optimizer.compute_gradient from guided tour
  docs/notebooks/flax_guided_tour.ipynb
Labels: cla: yes

#169 set __qualname__ for partial, shared, and module_method.
  flax/nn/base.py
  tests/nn_test.py
Labels: cla: yes

#109 Update nlp_seq example README.md
  examples/nlp_seq/README.md
  examples/nlp_seq/train.py
Labels: cla: yes, example

#168 Seq2Seq: Add back a bit of nn.sochastic now that `init_shape` issue is resolved.
  examples/seq2seq/train.py
  examples/seq2seq/train_test.py
Labels: cla: yes

#172 Add scheduled sampling howto for seq2seq example.
  docs/howtos.rst
  howtos/diffs/scheduled-sampling.diff
Labels: cla: yes

#177 Fix issubclass bug
  flax/nn/base.py
  tests/nn_test.py
Labels: cla: yes

#188 Fix broken f-strings
  flax/nn/base.py
  flax/struct.py
Labels: cla: yes

#195 Rename `model_def` to `module` in all instances.
  docs/notebooks/flax_guided_tour.ipynb
  examples/cifar10/train.py
  examples/imagenet/train.py
  examples/lm1b/Colab_Language_Model.ipynb
  examples/lm1b/train.py
  examples/nlp_seq/train.py
  examples/sst2/model.py
  examples/vae/train.py
  examples/wip/moco/train_moco.py
  tests/nn_attention_test.py
  tests/serialization_test.py
Labels: cla: yes

#197 Fix typo.
  flax/nn/base.py
Labels: cla: yes

#199 Add github status reporting to github Build action.
  .github/workflows/build.yml
Labels: cla: yes

#201 Add Adagrad and RMSProp optimizers
  flax/optim/__init__.py
  flax/optim/adagrad.py
  flax/optim/rmsprop.py
  tests/optim_test.py
Labels: cla: yes

#184 Add init_by_shape method usage example.
  flax/nn/base.py
Labels: cla: yes, documentation

#205 Fix typos.
  examples/imagenet/train.py
  flax/struct.py
Labels: cla: yes

#133 Add WMT translation example.
  examples/wmt/README.md
  examples/wmt/bleu.py
  examples/wmt/decode.py
  examples/wmt/input_pipeline.py
  examples/wmt/models.py
  examples/wmt/train.py
Labels: cla: yes, enhancement, example

#198 Fix lm1b example: checkpoint loading was not done correctly; the refe…
  examples/lm1b/decode.py
  examples/lm1b/train.py
Labels: bug, cla: yes, example

#206 Make the tests run by transforming warnings into errors
  pytest.ini
  tests/nn_attention_test.py
  tests/run_all_tests.sh
Labels: cla: yes

#217 fix optimizing with no parameters
  flax/optim/base.py
  tests/optim_test.py
Labels: cla: yes

#200 Update MNIST input pipeline
  examples/mnist/README.md
  examples/mnist/train.py
Labels: cla: yes

#203 Update VAE input pipeline.
  examples/vae/reconstruction.png
  examples/vae/sample.png
  examples/vae/train.py
Labels: cla: yes

#183 Add PixelCNN++ example
  examples/pixelcnn/README.md
  examples/pixelcnn/input_pipeline.py
  examples/pixelcnn/model_test.py
  examples/pixelcnn/pixelcnn.py
  examples/pixelcnn/train.py
Labels: cla: yes, example

#178 make stateful check work on pytrees
  flax/nn/base.py
  flax/nn/utils.py
  tests/nn_test.py
Labels: cla: yes

#207 Deprecating compute_gradients
  examples/imagenet/train.py
  examples/sst2/train.py
  flax/optim/base.py
  tests/optim_test.py
Labels: cla: yes

#218 Fast WMT input pipeline with sentencepiece tokenization and packed examples.
  examples/wmt/README.md
  examples/wmt/bleu.py
  examples/wmt/decode.py
  examples/wmt/input_pipeline.py
  examples/wmt/models.py
  examples/wmt/train.py
  flax/nn/attention.py
Labels: cla: yes

#228 Implement sampling for PixelCNN++ example
  examples/pixelcnn/README.md
  examples/pixelcnn/sample.png
  examples/pixelcnn/sample.py
Labels: cla: yes

#229 Eliminate weight_decay guard.
  flax/optim/adam.py
Labels: cla: yes

#224 Add single train step test for GNNs.
  examples/graph/train.py
  examples/graph/train_test.py
Labels: cla: yes
