Repository google/flax, pull requests merged in 2020-12, with the labels that each got.

#698 Update Community Examples
  docs/examples.rst
Labels: cla: yes

#696 Fix setup in transformed class
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
  tests/linen/module_test.py
Labels: cla: yes

#702 Re-add flax install to doc requirements
  docs/README.md
  docs/requirements.txt
Labels: cla: yes

#657 A wide pass on docs
  README.md
  docs/faq.md
  docs/flax.linen.rst
  docs/flax.nn.rst
  docs/index.rst
  docs/overview.md
  docs/philosophy.md
  examples/README.md
  flax/linen/README.md
  flax/linen/__init__.py
Labels: cla: yes

#681 Lint (deprecated) flax.nn.base (NN base modules for JAX)
  flax/nn/base.py
Labels: cla: yes

#647 Replace flax named_call with upstream version jax.named_call
  flax/core/lift.py
  flax/core/named_call.py
  setup.py
Labels: Priority: P2 - medium, cla: yes

#680 Lift module cleanup
  docs/notes/lift.md
  flax/core/lift.py
  flax/core/tracers.py
  tests/core/design/core_tied_autoencoder_test.py
Labels: cla: yes

#706 Relax parameter attribute check
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#714 Fix Linen README link to core design tests
  flax/linen/README.md
Labels: cla: yes

#716 Version bump to 0.3
  CHANGELOG.md
  flax/version.py
Labels: cla: yes

#717 Fixes validation steps.
  linen_examples/imagenet/train.py
Labels: cla: yes

#648 Add optimized LSTM cell.
  flax/linen/__init__.py
  flax/linen/recurrent.py
  flax/nn/__init__.py
  flax/nn/recurrent.py
  tests/linen/linen_test.py
  tests/nn_test.py
Labels: Priority: P2 - medium, Status: in progress, Type: enhancement, cla: yes

#720 Update CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes

#721 Add OptimizedLSTMCell to docs.
  docs/flax.linen.rst
  docs/flax.nn.rst
Labels: cla: yes

#708 Updates imagenet,mnist examples with result tables
  linen_examples/imagenet/README.md
  linen_examples/mnist/README.md
Labels: Priority: P2 - medium, Status: in progress, Type: maintenance, cla: yes

#723 Correct typo in linen/module.py
  flax/linen/module.py
Labels: cla: yes

#724 Add Stochastic to documentation
  docs/flax.linen.rst
Labels: cla: yes

#737 Decreases time needed to run tests.
  linen_examples/imagenet/configs/default.py
  linen_examples/imagenet/models.py
  linen_examples/imagenet/models_test.py
  linen_examples/imagenet/train.py
  linen_examples/imagenet/train_test.py
  setup.py
  tests/run_all_tests.sh
Labels: cla: yes

#741 disable LLVM optimization on tests with long compilation times
  linen_examples/imagenet/models_test.py
  linen_examples/imagenet/train_test.py
  linen_examples/wmt/train_test.py
Labels: Priority: P2 - medium, Status: accepted, Type: maintenance, cla: yes

#740 Add support for single example pooling
  flax/linen/pooling.py
  tests/linen/linen_test.py
Labels: Priority: P2 - medium, Status: in progress, Type: enhancement, cla: yes

#751 Fixes build workflow (currently timeout when installing dependencies).
  .github/workflows/build.yml
  setup.py
Labels: cla: yes

#757 Fix variable exists check
  CHANGELOG.md
  flax/core/scope.py
Labels: cla: yes

#770 Standardize doc names with capital letters
  docs/design_notes/design_notes.rst
  docs/design_notes/linen_design_principles.rst
  docs/examples.rst
  docs/index.rst
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/index.rst
  docs/notebooks/jax_for_the_impatient.ipynb
  docs/patterns/flax_patterns.rst
  docs/patterns/state_params.rst
Labels: cla: yes

#778 Reorg docs left pane, rename "patterns" to HOWTOs
  README.md
  docs/deprecated_howtos/checkpointing.rst
  docs/deprecated_howtos/distributed-training.rst
  docs/deprecated_howtos/ensembling.rst
  docs/deprecated_howtos/howtos-howto.md
  docs/deprecated_howtos/index.rst
  docs/deprecated_howtos/polyak-averaging.rst
  docs/deprecated_howtos/scheduled-sampling.rst
  docs/design_notes/design_notes.rst
  docs/howtos.rst
  docs/howtos/state_params.rst
  docs/index.rst
  docs/patterns/flax_patterns.rst
  howtos/scripts/check_howto_diffs.sh
Labels: cla: yes
