Repository google/flax, pull requests merged in 2020-05, with the labels that each got.

#236 fix lm1b input_pipeline bin_and_batch bug
  examples/lm1b/input_pipeline.py
Labels: cla: yes

#242 Replace shuffle with permutation in graph example test
  examples/graph/train_test.py
Labels: cla: yes

#243 make jax_utils.replicate match pmap devices
  flax/jax_utils.py
Labels: cla: yes

#144 Regression testing for Flax examples
  examples/cifar10/train.py
  examples/cifar10/train_benchmark.py
  examples/imagenet/train_benchmark.py
  examples/mnist/train.py
  examples/mnist/train_benchmark.py
  flax/testing/__init__.py
  flax/testing/benchmark.py
Labels: cla: yes, example

#245 wmt should actually use specified tfds eval set
  examples/wmt/input_pipeline.py
Labels: cla: yes

#241 Run unit tests for each affected example in a howto
  howtos/scripts/apply_howto_diffs.sh
Labels: cla: yes

#240 Adding lightweight support for community examples
  .github/ISSUE_TEMPLATE/example_request.md
  README.md
  examples/README.md
Labels: cla: yes, enhancement, example

#253 Flush MNIST summaries.
  examples/mnist/train.py
Labels: cla: yes

#255 Only pack examples directories when packing howtos
  howtos/scripts/pack_howto_diffs.sh
Labels: cla: yes

#252 Fix nits in testing/benchmark.py
  flax/testing/benchmark.py
Labels: cla: yes

#251 Update howtos so all diffs can be applied and all pass example tests
  howtos/diffs/distributed-training.diff
  howtos/diffs/ensembling.diff
  howtos/diffs/polyak-averaging.diff
Labels: cla: yes

#227 Add code coverage, upload report to codecov.io, and display badge
  .github/workflows/build.yml
  README.md
  setup.cfg
  setup.py
  tests/run_all_tests.sh
Labels: cla: yes

#225 Refactor mnist/train_test.py from testing single epoch to single train step
  examples/mnist/train_test.py
Labels: cla: yes

#257 support axis index groups for distributed batchnorm
  flax/nn/normalization.py
Labels: cla: yes

#248 Split check and apply steps for howtos
  .github/workflows/build.yml
  howtos/diffs/distributed-training.diff
  howtos/diffs/ensembling.diff
  howtos/diffs/polyak-averaging.diff
  howtos/scripts/apply_howto_diffs.sh
  howtos/scripts/check_howto_diffs.sh
Labels: cla: yes

#256 Update HOWTO HOWTOS for resolving conflicts.
  docs/howtos-howto.md
Labels: cla: yes

#270 Only install dataclasses dep in python 3.6
  setup.py
Labels: cla: yes

#239 Change RMSProp beta2 default to 0.9
  flax/optim/rmsprop.py
Labels: cla: yes, question

#258 Migrate TF1 compat Summary writer to TF2 in metrics/tensorboard.py
  flax/metrics/tensorboard.py
  pytest.ini
  tests/tensorboard_test.py
Labels: cla: yes

#273 Parse 'tensor' field in summary value instead of 'summary_value'.
  flax/testing/benchmark.py
Labels: cla: yes

#266 Adds link to DQN example to the examples table
  examples/README.md
Labels: cla: yes

#281 Add --model_dir flag as the training code requires this field to be set.
  examples/mnist/README.md
Labels: cla: yes

#278 Added checkpointing howto
  docs/howtos.rst
  howtos/diffs/checkpointing.diff
Labels: cla: yes

#295 Clean up check_howto_diffs.sh
  howtos/scripts/check_howto_diffs.sh
Labels: cla: yes

#296 Use Jax RNG for data shuffling in MNIST example.
  examples/mnist/train.py
  howtos/diffs/checkpointing.diff
  howtos/diffs/distributed-training.diff
  howtos/diffs/ensembling.diff
  howtos/diffs/polyak-averaging.diff
Labels: cla: yes

#298 Update tensorboard tests
  tests/tensorboard_test.py
Labels: cla: yes

#297 Add *.rej to .gitignore
  .gitignore
Labels: cla: yes

#285 Fixing LICENSE info in setup.py
  setup.py
Labels: cla: yes
