Repository google/flax, pull requests merged in 2020-10, with the labels that each got.

#505 Update CHANGELOG: Add new header for v0.2.2
  CHANGELOG.md
Labels: cla: yes

#454 Use automasking in seq2seq example
  linen_examples/seq2seq/README.md
  linen_examples/seq2seq/train.py
  linen_examples/seq2seq/train_test.py
Labels: cla: yes

#507 Updates README "Getting involved".
  README.md
  tests/download_dataset_metadata.sh
  tests/run_all_tests.sh
Labels: cla: yes

#496 Removes CIFAR10 example.
  README.md
  examples/README.md
  examples/cifar10/README.md
  examples/cifar10/input_pipeline.py
  examples/cifar10/models/__init__.py
  examples/cifar10/models/pyramidnet.py
  examples/cifar10/models/utils.py
  examples/cifar10/models/wideresnet.py
  examples/cifar10/models/wideresnet_shakeshake.py
  examples/cifar10/train.py
  examples/cifar10/train_benchmark.py
Labels: Priority: medium - P2, Status: in progress, Type: example, cla: yes

#514 Write hparams MNIST and ImageNet linen examples.
  linen_examples/imagenet/imagenet_lib.py
  linen_examples/mnist/mnist_lib.py
Labels: cla: yes

#516 Fix warning about float64 types
  pytest.ini
Labels: cla: yes

#535 Fix Module dataclass handling of inheritance.
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#531 Fix and simplify pixelcnn learning rate
  linen_examples/pixelcnn/train.py
Labels: cla: yes

#536 Adds some documentation to functional core and some tests
  flax/core/scope.py
  tests/core/scope_test.py
Labels: cla: yes

#541 Ppo daemon fix
  examples/ppo/agent.py
  examples/ppo/ppo_main.py
Labels: cla: yes

#534 Allow assignment of mixed Module pytrees in setup.
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes

#530 Check shape consistency for params
  flax/core/scope.py
  flax/linen/module.py
  tests/core/scope_test.py
Labels: cla: yes

#529 Improved mutable collection handling
  flax/core/lift.py
  flax/core/scope.py
  tests/core/scope_test.py
  tests/linen/module_test.py
Labels: cla: yes

#493 Adds MNIST example Jupyter/Colab notebook.
  docs/notebooks/annotated_mnist_example._ipynb
  linen_examples/mnist/README.md
  linen_examples/mnist/mnist.ipynb
Labels: Priority: medium - P2, Status: review needed, Type: enhancement, cla: yes

#549 Preserve nested dict in MultiOptimizer
  flax/optim/base.py
  flax/traverse_util.py
  tests/optim_test.py
  tests/traverse_util_test.py
Labels: cla: yes

#526 Add DCGAN example
  examples/README.md
Labels: Priority: P3 - low, Status: in progress, Type: example, cla: yes

#553 Test with named_call active
  tests/run_all_tests.sh
Labels: cla: yes

#555 Fix transient module-state handling by transforms.
  flax/linen/transforms.py
Labels: cla: yes

#556 Avoid nested FrozenDic during state restore.
  flax/core/frozen_dict.py
Labels: cla: yes

#538 use core reservation check in linen.
  flax/linen/module.py
Labels: Priority: P1 - high, Status: in progress, Type: bug, cla: yes

#557 Make FrozenDict constructor freeze correctly.
  flax/core/frozen_dict.py
Labels: cla: yes

#508 PPO Linen example
  linen_examples/ppo/README.md
  linen_examples/ppo/agent.py
  linen_examples/ppo/default_config.py
  linen_examples/ppo/env_utils.py
  linen_examples/ppo/models.py
  linen_examples/ppo/ppo_lib.py
  linen_examples/ppo/ppo_lib_test.py
  linen_examples/ppo/ppo_main.py
  linen_examples/ppo/requirements.txt
  linen_examples/ppo/seed_rl_atari_preprocessing.py
  linen_examples/ppo/test_episodes.py
Labels: Priority: P2 - medium, Status: accepted, Status: in progress, Type: example, cla: yes

#560 Better input checks
  flax/core/lift.py
  flax/core/scope.py
  tests/core/lift_test.py
  tests/core/scope_test.py
Labels: cla: yes

#581 Graduate Linen out of alpha
  flax/linen/README.md
Labels: cla: yes

#585 Fix jax bfloat16 array handling in msgpack serialization.
  flax/serialization.py
  tests/serialization_test.py
Labels: cla: yes

#583 Update README to linen
  README.md
Labels: cla: yes
