Repository google/flax, pull requests merged in 2021-06, with the labels that each got.

#1350 Adds reference to matthias-wright/flaxmodels
  docs/examples.rst
Labels: cla: yes

#1351 Fix citations
  examples/imagenet/README.md
Labels: cla: yes, pull ready

#1354 Fix NamedTuples being converted to tuples in Module
  CHANGELOG.md
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1362 Fix spelling in MNIST Colab
  examples/mnist/mnist.ipynb
Labels: cla: yes, pull ready

#1361 Updates examples/vae to use Optax.
  examples/vae/README.md
  examples/vae/requirements.txt
  examples/vae/train.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1358 Updates docs for Optax.
  docs/annotated_mnist.md
  docs/flax.optim.rst
  docs/flax.training.rst
  docs/index.rst
  docs/notebooks/annotated_mnist.ipynb
  docs/notebooks/annotated_mnist_example._ipynb
  docs/notebooks/flax_basics.ipynb
  examples/imagenet/requirements.txt
  examples/mnist/README.md
  examples/mnist/train.py
  flax/optim/__init__.py
  flax/training/lr_schedule.py
  flax/training/train_state.py
Labels: cla: yes, pull ready

#1365 Add typing stub for Module __call__
  flax/linen/module.py
Labels: cla: yes, pull ready

#1368 Change unhashable module exception type to TypeError.
  flax/linen/module.py
  setup.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1371 Adds google/vision_transformer example link.
  docs/examples.rst
Labels: cla: yes

#1379 Correct typo: n --> np (numpy)
  docs/notebooks/jax_for_the_impatient.ipynb
Labels: cla: yes

#1372 Updates imagenet Colab & checkpoints for Optax.
  examples/imagenet/README.md
  examples/imagenet/imagenet.ipynb
Labels: Priority: P1 - high, cla: yes, pull ready
