Repository google/flax, pull requests merged in 2021-04, with the labels that each got.

#1193 Fix link template for error docstrings on RTD
  flax/errors.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1194 Remove explicit omnistaging enabling
  examples/linen_design_test/attention_simple.py
  examples/linen_design_test/autoencoder.py
  examples/linen_design_test/dense.py
  examples/linen_design_test/linear_regression.py
  examples/linen_design_test/mlp_explicit.py
  examples/linen_design_test/mlp_inline.py
  examples/linen_design_test/mlp_lazy.py
  examples/linen_design_test/tied_autoencoder.py
  examples/linen_design_test/weight_std.py
  examples/mnist/train_test.py
  examples/seq2seq/train_test.py
  tests/linen/dotgetter_test.py
  tests/linen/linen_attention_test.py
  tests/linen/linen_linear_test.py
  tests/linen/linen_test.py
  tests/linen/linen_transforms_test.py
  tests/linen/module_test.py
  tests/linen/toplevel_test.py
Labels: cla: yes, pull ready

#1011 FLIP #1009: New Optimizer API
  docs/flip/1009-optimizer-api.md
  docs/flip/README.md
Labels: Priority: P1 - high, cla: yes

#1204 Allow a small bugfix to be send as a PR straight away
  .github/pull_request_template.md
Labels: cla: yes

#1203 Fix super calls in compact & setup
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1200 Checkpoint fix
  flax/training/checkpoints.py
Labels: cla: yes, pull ready

#1202 Ask dataclass to generate __hash__ only if not implemented yet.
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1210 Add missing @ from function annotation in dynamic_scale.py
  flax/optim/dynamic_scale.py
Labels: cla: yes, pull ready

#711 Add early stopping to flax.training
  flax/training/early_stopping.py
  tests/early_stopping_test.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1236 fix wrong tuple type in Scope constructor.
  flax/core/scope.py
Labels: cla: yes, pull ready

#1243 Adds FLIPs link to main RST nav.
  docs/index.rst
Labels: cla: yes

#1237 Fix DenseGeneral bug
  flax/linen/linear.py
  tests/linen/linen_linear_test.py
Labels: cla: yes, pull ready

#1242 Git ignores .devcontainer
  .gitignore
Labels: cla: yes, pull ready

#1241 Delete redundant directory
  flax/nn/.vscode/settings.json
Labels: Priority: P2 - medium, cla: yes, pull ready

#1254 Don't update batch statistics during initialization.
  CHANGELOG.md
  flax/linen/normalization.py
  tests/linen/linen_test.py
Labels: cla: yes, pull ready

#1228 Improves .sow() example HOWTO.
  docs/flax.linen.rst
  docs/howtos/extracting_intermediates.rst
  flax/linen/module.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1256 Expose deny list in flax.core and flax.linen
  flax/core/__init__.py
  flax/core/scope.py
  flax/linen/__init__.py
Labels: cla: yes, pull ready

#1133 Add SST-2 text classification example (Flax Linen).
  CHANGELOG.md
  examples/sst2/README.md
  examples/sst2/build_vocabulary.py
  examples/sst2/configs/default.py
  examples/sst2/input_pipeline.py
  examples/sst2/input_pipeline_test.py
  examples/sst2/main.py
  examples/sst2/models.py
  examples/sst2/models_test.py
  examples/sst2/requirements.txt
  examples/sst2/sst2.ipynb
  examples/sst2/train.py
  examples/sst2/vocab.txt
  examples/sst2/vocabulary.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1251 Updates examples/imagenet to use Optax.
  docs/flip/1009-optimizer-api.md
  examples/imagenet/train.py
  examples/imagenet/train_test.py
  flax/training/train_state.py
  setup.py
Labels: cla: yes, pull ready

#1258 Fix places that were passing jnp.array where a shape was expected.
  examples/lm1b/models.py
  examples/wmt/models.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1262 Fix behavior of Embed when embedding is a numpy array
  flax/linen/linear.py
  tests/linen/linen_linear_test.py
Labels: cla: yes, pull ready

#1259 Fix path for installing sst2 requirements
  examples/sst2/sst2.ipynb
Labels: cla: yes, pull ready

#1272 Fix git command that add upstream
  docs/contributing.md
Labels: cla: yes

#1278 Fix some typos in contributing.md
  docs/contributing.md
Labels: cla: yes

#1275 Add proper cache behavior for lift.jit
  flax/core/lift.py
  tests/core/lift_test.py
Labels: cla: yes, pull ready

#1284 Fix intermediates during init
  CHANGELOG.md
  docs/howtos/extracting_intermediates.rst
  flax/core/lift.py
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready
