Repository google/flax, pull requests merged in 2021-03, with the labels that each got.

#1054 Fix misspelt
  docs/annotated_mnist.md
  docs/deprecated_howtos/index.rst
  examples/lm1b_deprecated/README.md
  examples/ppo/README.md
Labels: cla: yes, pull ready

#1055 Release 0.3.2
  CHANGELOG.md
  README.md
  contributing.md
  flax/__init__.py
  flax/nn/__init__.py
  flax/nn/base.py
  flax/version.py
Labels: cla: yes, pull ready

#1063 Adding ignore for flax.nn deprecation warning
  pytest.ini
Labels: cla: yes

#1059 Add Model Surgery HOWTO
  docs/howtos/model_surgery.rst
  docs/index.rst
Labels: Priority: P1 - high, cla: yes

#1047 Makes sure RHS of codediff directive blocks are tested
  docs/_ext/codediff.py
  docs/_ext/codediff_test.py
  docs/howtos/ensembling.rst
  docs/howtos/extracting_intermediates.rst
  docs/howtos/lr_schedule.rst
  docs/howtos/state_params.rst
  docs/requirements.txt
Labels: Priority: P1 - high, cla: yes

#1018 HOWTO: Implementing a Squeeze and Excite block
  docs/howtos/squeeze_and_excite.rst
Labels: Priority: P2 - medium, cla: yes

#1069 Stores logging output in workdir.
  examples/imagenet/main.py
  examples/lm1b/main.py
  examples/mnist/main.py
  examples/pixelcnn/main.py
  examples/ppo/ppo_main.py
  examples/wmt/main.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1071 Revert "HOWTO: Implementing a Squeeze and Excite block"
  docs/howtos/squeeze_and_excite.rst
Labels: cla: yes

#1082 Update ensembling.rst
  docs/howtos/ensembling.rst
Labels: cla: yes

#1070 Moves all errors in scope.py to errors.py
  flax/core/scope.py
  flax/errors.py
  flax/linen/module.py
  tests/core/lift_test.py
  tests/core/scope_test.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1075 Fixes a bug in Module and adds test
  CHANGELOG.md
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1083 Revert "Fixes a bug in Module and adds test"
  CHANGELOG.md
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1078 implement functional init/apply and bind.
  docs/flax.linen.rst
  examples/vae/train.py
  flax/core/__init__.py
  flax/core/scope.py
  flax/linen/__init__.py
  flax/linen/module.py
  tests/linen/module_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1093 Creates logdir before logging to files.
  examples/imagenet/main.py
  examples/lm1b/main.py
  examples/mnist/main.py
  examples/pixelcnn/main.py
  examples/ppo/ppo_main.py
  examples/wmt/main.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1088 Improve Flax Linen API __call__ and __init__ formatting in docstrings
  flax/linen/module.py
Labels: cla: yes, pull ready

#1099 Show PyTreeNode on RTD
  docs/flax.struct.rst
  flax/struct.py
Labels: cla: yes, pull ready

#1084 Fixes a bug in Module
  flax/linen/module.py
  tests/linen/module_test.py
Labels: Priority: P3 - low, cla: yes, pull ready

#1105 Improve Actions hygiene
  .github/workflows/build.yml
Labels: cla: yes

#1100 improve bind docs
  flax/linen/module.py
Labels: cla: yes, pull ready

#1113 mnist: tweak demo call
  examples/mnist/README.md
Labels: Priority: P0 - critical, Status: accepted, cla: yes, pull ready

#1112 wmt: tweak readme example config
  examples/wmt/README.md
Labels: Priority: P0 - critical, cla: yes, pull ready

#1119 Remove deprecated LM1b example
  examples/lm1b_deprecated/Colab_Language_Model.ipynb
  examples/lm1b_deprecated/README.md
  examples/lm1b_deprecated/decode.py
  examples/lm1b_deprecated/input_pipeline.py
  examples/lm1b_deprecated/models.py
  examples/lm1b_deprecated/train.py
  examples/lm1b_deprecated/train_test.py
Labels: cla: yes, pull ready

#1116 Remove FrozenDict checks to determine mutability.
  flax/core/lift.py
  flax/core/scope.py
  tests/core/scope_test.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1127 Fixes a bug in Module and adds test
  CHANGELOG.md
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1120 Fix checkpoint overwrite
  CHANGELOG.md
  flax/errors.py
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: cla: yes, pull ready

#1121 lm1b: tweak readme command
  examples/lm1b/README.md
Labels: Priority: P2 - medium, cla: yes, pull ready

#1117 Updates docstrings on module.py
  flax/linen/module.py
Labels: cla: yes, pull ready

#1134 MNIST Colab : Adds a link to imagenet Colab showing use of TPUs.
  examples/mnist/mnist.ipynb
Labels: Priority: P3 - low, cla: yes, pull ready

#1131 Fix README instructions in PixelCNN example
  examples/pixelcnn/README.md
  examples/pixelcnn/input_pipeline.py
Labels: cla: yes, pull ready

#1092 use config file, add note about how to use bucket for data
  examples/imagenet/README.md
Labels: Priority: P1 - high, cla: yes, pull ready

#1135 Checks no param is matched multiple times.
  flax/optim/base.py
  tests/optim_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1174 Add a comment to MultiOptimizer
  flax/optim/base.py
Labels: cla: yes, pull ready

#1179 Small updates to main README
  README.md
Labels: cla: yes, pull ready

#1175 Fixes ModelParamTraversal & value-dependent filter
  flax/optim/base.py
  tests/optim_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1072 Moves errors in module.py to errors.py [1/2]
  CHANGELOG.md
  docs/howtos/extracting_intermediates.rst
  docs/index.rst
  flax/core/scope.py
  flax/errors.py
  flax/linen/module.py
  tests/linen/module_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1107 Add documentation for linen transforms
  docs/flax.linen.rst
  flax/core/lift.py
  flax/core/scope.py
  flax/linen/transforms.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1118 Remove legacy HOWTOs
  howtos/README.md
  howtos/diffs/checkpointing.diff
  howtos/diffs/distributed-training.diff
  howtos/diffs/ensembling.diff
  howtos/diffs/polyak-averaging.diff
  howtos/diffs/scheduled-sampling.diff
  howtos/scripts/apply_howto_diffs.sh
  howtos/scripts/check_howto_diffs.sh
  howtos/scripts/pack_howto_diffs.sh
Labels: Priority: P3 - low, cla: yes, pull ready

#1181 Improve various docs on contributing and adds PR template
  .github/pull_request_template.md
  contributing.md
  docs/README.md
  docs/contributing.md
Labels: Priority: P2 - medium, cla: yes

#1187 rm _check_omnistaging
  flax/linen/module.py
Labels: cla: yes, pull ready

#1180 Preserve original parameter structure in MultiOptimizer state
  flax/optim/base.py
  tests/optim_test.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1190 Release 0.3.3
  CHANGELOG.md
  README.md
  flax/version.py
Labels: cla: yes, pull ready

#1191 Attention: require `deterministic` only if using dropout.
  flax/linen/attention.py
Labels: cla: yes, pull ready
