Repository google/flax, pull requests merged in 2021-12, with the labels that each got.

#1692 Fix child scope rng reuse.
  flax/core/lift.py
  flax/core/scope.py
  tests/core/core_scope_test.py
  tests/linen/linen_module_test.py
Labels: cla: yes, pull ready

#1694 Adds link to https://github.com/n2cholas/jax-resnet
  examples/README.md
Labels: cla: yes, pull ready

#1693 Numerically stable weight norm
  flax/optim/weight_norm.py
  tests/optim_test.py
Labels: cla: yes, pull ready

#1696 Remove cyclic refs from scope
  flax/core/lift.py
  flax/core/scope.py
  tests/core/core_scope_test.py
Labels: cla: yes, pull ready

#1697 Updates TPU instructions
  docs/overview.md
Labels: cla: yes

#1691 Add `unroll` to `jax_utils.scan_in_dim`
  flax/jax_utils.py
Labels: cla: yes, Priority: P2 - medium, pull ready

#1698 Add error for empty scopes.
  flax/core/scope.py
  flax/errors.py
  tests/core/core_lift_test.py
  tests/core/core_scope_test.py
Labels: cla: yes, pull ready

#1703 correct axis resolution in case of repeated axis in the logica axis r…
  flax/linen/partitioning.py
  tests/linen/partitioning_test.py
Labels: pull ready

#1711 Fix failing lm1b tests.
  pytest.ini
Labels: pull ready

#1716 Fix lost mutation bug in transforms on nested scopes.
  flax/core/scope.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#1710 Expose put_variable function to Module.
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#1720 add __eq__ and __hash__ for scopes
  flax/core/scope.py
Labels: pull ready

#1739 Add param_dtype argument to linen Modules
  CHANGELOG.md
  flax/linen/attention.py
  flax/linen/linear.py
  flax/linen/normalization.py
  flax/linen/recurrent.py
  tests/linen/linen_module_test.py
Labels: pull ready

#1738 Implement custom vjp
  CHANGELOG.md
  docs/flax.linen.rst
  flax/core/lift.py
  flax/linen/__init__.py
  flax/linen/transforms.py
  tests/core/design/core_custom_vjp_test.py
  tests/linen/linen_transforms_test.py
Labels: pull ready
