Repository google/flax, pull requests merged in 2021-08, with the labels that each got.

#1470 Add jraph to test dependencies in setup.py.
  setup.py
Labels: cla: yes

#1471 Several small docs fixes
  README.md
  docs/design_notes/arguments.md
  docs/howtos/extracting_intermediates.rst
  docs/howtos/lr_schedule.rst
  docs/howtos/state_params.rst
  docs/notebooks/annotated_mnist.ipynb
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/linen_intro.ipynb
  flax/linen/module.py
Labels: cla: yes, pull ready

#1475 Fix cloudpickle serialization of wrapped Module methods.
  flax/linen/module.py
Labels: cla: yes, pull ready

#1478 Add autocomplete support for Module and struct.dataclass.
  CHANGELOG.md
  flax/linen/module.py
  flax/struct.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1397 Handle passing Variables as arguments in lifted transforms
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, Priority: P2 - medium, pull ready

#1456 Create a proper error for using vanilla jax transforms
  flax/core/tracers.py
  flax/errors.py
Labels: cla: yes, pull ready

#1477 Bumps examples/cloud script versions.
  examples/cloud/README.md
  examples/cloud/launch_gce.py
  examples/cloud/startup_script.sh
Labels: cla: yes, pull ready

#1479 Updates `examples/lm1b` to use Optax
  examples/lm1b/README.md
  examples/lm1b/configs/default.py
  examples/lm1b/main.py
  examples/lm1b/requirements.txt
  examples/lm1b/train.py
Labels: cla: yes, pull ready

#1502 Update flax.optim.rst
  docs/flax.optim.rst
Labels: cla: yes

#1500 Adds NLP example references.
  docs/examples.rst
Labels: cla: yes

#1499 Plumb through the prevent_cse kwarg for jax remat.
  flax/core/lift.py
  flax/linen/transforms.py
Labels: cla: yes, pull ready
