Repository google/flax, pull requests merged in 2021-01, with the labels that each got.

#672 Adding missing docs in RTD
  docs/flax.optim.rst
  docs/flax.serialization.rst
  docs/flax.traverse_util.rst
  docs/index.rst
  flax/optim/adafactor.py
  flax/optim/adam.py
  flax/optim/weight_norm.py
  flax/traverse_util.py
Labels: cla: yes, pull ready

#795 Fix broken document link in italic notation
  docs/notebooks/flax_basics.ipynb
Labels: cla: yes

#794 Fix the display of math expressions in document
  docs/notebooks/jax_for_the_impatient.ipynb
Labels: cla: yes

#752 move DCGAN community example from deprecated to Linen
  docs/examples.rst
Labels: cla: yes

#779 Document `make_rng` and correct docstring
  docs/flax.linen.rst
  flax/linen/module.py
Labels: cla: yes, pull ready

#809 fix typo in community examples that breaks MD table formatting
  docs/examples.rst
Labels: cla: yes

#736 Adds flip/ for Flax improvement processes.
  docs/flip/0000-template.md
  docs/flip/README.md
Labels: Priority: P1 - high, cla: yes, pull ready

#831 Remove hard coded test threads.
  tests/run_all_tests.sh
Labels: cla: yes

#832 Fix opencv requirement in Docker setup.
  dev/.devcontainer/Dockerfile
Labels: Priority: P2 - medium, Status: blocked, cla: yes

#797 Fix missing `use_` prefix typos in documentation.
  flax/linen/normalization.py
Labels: cla: yes, pull ready

#823 Linen `Module` instances are now Frozen after `setup` has been called.
  CHANGELOG.md
  flax/linen/linear.py
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#836 Fix breaking test
  tests/linen/linen_test.py
Labels: cla: yes, pull ready

#839 Fix another case of isInstance test
  tests/linen/linen_test.py
Labels: cla: yes, pull ready

#840 build status badge
  README.md
Labels: Priority: P1 - high, cla: yes, pull ready

#822 ModelParamTraversal for linen
  CHANGELOG.md
  flax/optim/base.py
  tests/optim_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#838 Add empty lines to CHANGELOG
  CHANGELOG.md
Labels: Priority: P1 - high, cla: yes, pull ready

#829 Fixes some typos mentioned in #828.
  linen_examples/mnist/mnist.ipynb
  linen_examples/mnist/train.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#884 Delete old examples/, rename linen_examples/ -> examples/
  .github/workflows/apply-howto-branches.yml
  .github/workflows/build.yml
  docs/examples.rst
  docs/notebooks/linen_intro.ipynb
  linen_examples/README.md
  linen_examples/vae/results/.gitignore
Labels: cla: yes, pull ready

#909 Updates optimizer docstrings and RTD
  docs/flax.optim.rst
  flax/optim/base.py
Labels: cla: yes, pull ready

#841 [flax/core/scope.py] Rename "Arguments:" to "Args:"
  flax/core/scope.py
Labels: cla: yes, pull ready

#925 Use doctest for new HOWTOs, instead of our old diff system
  docs/README.md
  docs/conf.py
  docs/format_howtos.py
  tests/run_all_tests.sh
Labels: cla: yes, pull ready

#931 Adds comment to "focus" of OptimizerDef.create()
  flax/optim/base.py
Labels: cla: yes, pull ready

#937 Generalize transform handling for nested attribute submodules.
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, pull ready

#871 Add some explanation to sync_batch_stats
  examples/imagenet/train.py
Labels: cla: yes, pull ready

#872 Add comment to prefetch_to_device explaining it is mostly useful for …
  flax/jax_utils.py
Labels: cla: yes, pull ready

#938 Call setup lazily.
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#908 Updates comment on Models
  flax/serialization.py
Labels: cla: yes, pull ready

#910 Clarifies usage of jit on Module.init
  flax/linen/module.py
Labels: cla: yes, pull ready

#951 Fix type in ImageNet/Resnet Example
  examples/imagenet/models.py
Labels: cla: yes, pull ready

#947 Add automatic giant array chunking in msgpack checkpoints.
  flax/serialization.py
  tests/serialization_test.py
Labels: cla: yes, pull ready

#950 Fix lazy setup bug
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#764 ✍️ Expand the Flax annotated MNIST image classification tutorial, port to the Linen API
  docs/annotated_mnist.md
Labels: Priority: P2 - medium, cla: yes, pull ready

#863 [README.md] Add missing word and adjust surround word wrap
  README.md
Labels: cla: yes, pull ready

#949 Proposal for better error messages
  docs/flax.errors.rst
  docs/index.rst
  flax/core/scope.py
  flax/errors.py
  tests/core/lift_test.py
  tests/core/scope_test.py
Labels: cla: yes, pull ready

#954 Minor README updates
  README.md
Labels: cla: yes, pull ready

#953 Proposal for a new HOWTO side-by-side view
  docs/_ext/codediff.py
  docs/_ext/codediff_test.py
  docs/_static/css/flax_theme.css
  docs/conf.py
Labels: cla: yes, pull ready

#964 Fix incorrect variable name in flax_basics.ipynb
  docs/notebooks/flax_basics.ipynb
Labels: cla: yes, pull ready
