Repository google/flax, pull requests merged in 2021-09, with the labels that each got.

#1511 Fix embedding field annotation
  flax/linen/linear.py
  tests/linen/linen_linear_test.py
Labels: cla: yes, pull ready

#1497 Added glorot and he initializers
  flax/linen/initializers.py
Labels: cla: yes, pull ready

#1514 Update flax/examples/{wmt, lm1b} parsing JAX config flags
  examples/lm1b/main.py
  examples/wmt/README.md
  examples/wmt/main.py
Labels: cla: yes, pull ready

#1518 Pad with zeros matching image type
  examples/pixelcnn/pixelcnn.py
Labels: cla: yes, pull ready

#1457 kwargs in remat and pack
  flax/core/lift.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, pull ready

#1522 remove remaining uses of deprecated host_id
  examples/imagenet/train.py
  examples/lm1b/train.py
  examples/wmt/train.py
Labels: cla: yes, pull ready

#1519 Add nowrap decorator for module methods.
  flax/errors.py
  flax/linen/__init__.py
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, pull ready

#1521 Correct incorrect shape note in ensembling.rst
  docs/howtos/ensembling.rst
Labels: cla: yes

#1524 Add flax logo in SVG and 3 PNG sizes.
  images/flax_logo.png
  images/flax_logo.svg
  images/flax_logo_250px.png
  images/flax_logo_500px.png
Labels: cla: yes, pull ready

#1526 Clean up pytest.ini
  pytest.ini
Labels: cla: yes

#1525 Separate ModelParamTraversal into traverse_util.
  docs/flax.optim.rst
  docs/flax.traverse_util.rst
  flax/optim/base.py
  flax/struct.py
  flax/traverse_util.py
  tests/optim_test.py
  tests/traverse_util_test.py
Labels: cla: yes, pull ready

#1531 Fix lifting rng splits
  CHANGELOG.md
  flax/core/lift.py
  flax/linen/__init__.py
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1536 Fix PixelCNN example
  examples/pixelcnn/train.py
Labels: cla: yes, pull ready

#1535 Remove Implicit rank promotion
  CHANGELOG.md
  examples/lm1b/temperature_sampler.py
  examples/lm1b/train_test.py
  examples/pixelcnn/pixelcnn.py
  examples/seq2seq/train.py
  examples/sst2/models.py
  flax/core/nn/linear.py
  flax/linen/linear.py
  flax/linen/normalization.py
  flax/linen/recurrent.py
  flax/nn/linear.py
  flax/nn/normalization.py
  flax/nn/recurrent.py
  flax/training/common_utils.py
  tests/core/design/core_dense_test.py
  tests/core/design/core_flow_test.py
  tests/linen/linen_transforms_test.py
  tests/run_all_tests.sh
Labels: cla: yes, pull ready

#1483 Add marker file for PEP 561: Distributing and Packaging Type Information
  flax/py.typed
  setup.py
Labels: cla: yes, pull ready

#1537 Enable traceback filtering of flax internal frames.
  docs/flax.config.rst
  docs/flax.traceback_util.rst
  docs/index.rst
  flax/config.py
  flax/core/lift.py
  flax/core/scope.py
  flax/jax_utils.py
  flax/linen/module.py
  flax/linen/transforms.py
  flax/traceback_util.py
  tests/traceback_util_test.py
Labels: cla: yes, Priority: P2 - medium, pull ready

#1547 Fix build using gym downgrade
  setup.py
Labels: cla: yes, pull ready

#1546 Automatically remove non-init attributes from dataclass hash/eq/repr
  flax/linen/linear.py
  flax/linen/module.py
Labels: cla: yes, pull ready

#1545 Unify normalization layers
  flax/linen/normalization.py
Labels: cla: yes, pull ready

#1551 Version 0.3.5
  CHANGELOG.md
  README.md
  flax/version.py
Labels: cla: yes, pull ready

#1557 Fix _is_valid_rngs for frozendict of rngs.
  flax/core/scope.py
  tests/core/scope_test.py
Labels: cla: yes, pull ready

#1485 Add jraph dependency for upcoming ogbg_molpcba example.
  setup.py
Labels: cla: yes, Priority: P1 - high

#1560 Forward experimental checkpoint policy option in lift.remat
  .github/workflows/build.yml
  CHANGELOG.md
  docs/flax.linen.rst
  flax/core/lift.py
  flax/linen/__init__.py
  flax/linen/transforms.py
  setup.py
  tests/core/design/core_big_resnets_test.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, pull ready

#1581 Map variables for linen
  CHANGELOG.md
  docs/flax.linen.rst
  flax/core/lift.py
  flax/core/scope.py
  flax/linen/__init__.py
  flax/linen/transforms.py
  tests/core/design/core_tied_autoencoder_test.py
  tests/core/design/core_weight_std_test.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, pull ready
