Repository google/flax, pull requests merged in 2021-05, with the labels that each got.

#1281 Fix minor typos in docs/contributing.md
  docs/contributing.md
Labels: cla: yes

#1274 Update install instructions for contributing.
  docs/contributing.md
Labels: cla: yes

#1280 Update CHANGELOG.md
  CHANGELOG.md
Labels: Priority: P2 - medium, cla: yes

#1300 Bumps JAX version to 0.2.13
  setup.py
Labels: cla: yes

#1301 Ignore `jax.host_{id,count}()` deprecation warning
  pytest.ini
Labels: cla: yes

#1295 Fix linen.scan docstring example.
  flax/linen/transforms.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1291 Expose `dot_product_attention_weights`
  docs/flax.linen.rst
  flax/linen/attention.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1307 Fix some typos
  flax/core/lift.py
  flax/core/scope.py
  flax/linen/module.py
  flax/linen/transforms.py
Labels: cla: yes, pull ready

#1302 Updates examples/mnist to use Optax.
  examples/mnist/mnist.ipynb
  examples/mnist/train.py
  examples/mnist/train_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1311 Use notify_all instead of notifyAll method that was deprecated in Python 3.10.
  flax/training/prefetch_iterator.py
Labels: cla: yes, pull ready

#1327 Don't pip install newest TF (see #1326)
  setup.py
Labels: cla: yes

#1318 New Flax release: v0.3.4
  CHANGELOG.md
  README.md
  flax/version.py
Labels: Priority: P2 - medium, cla: yes

#1314 Minor spelling corrections, JAX for the impatient docs
  docs/notebooks/jax_for_the_impatient.ipynb
Labels: cla: yes, pull ready

#1312 Add vmap + BatchNorm example to the state howto
  docs/howtos/state_params.rst
Labels: cla: yes, pull ready

#1323 Renames `train_state` to `state`.
  docs/flip/1009-optimizer-api.md
Labels: Priority: P2 - medium, cla: yes

#1267 Add design note on lifted transformations
  docs/conf.py
  docs/design_notes/lift.md
  docs/notes/lift.md
  docs/requirements.txt
Labels: Priority: P2 - medium, cla: yes, pull ready

#1324 Expose merge_param at top level of flax.linen.
  flax/linen/__init__.py
Labels: cla: yes, pull ready

#1276 Uses clu.metric_writer & adds config.log_every_step=100
  examples/imagenet/configs/default.py
  examples/imagenet/configs/tpu.py
  examples/imagenet/train.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1336 Add atari rom depencency
  setup.py
Labels: cla: yes, pull ready

#1338 Enhance JAX for the Impatient doc (Flax)
  docs/notebooks/jax_for_the_impatient.ipynb
Labels: cla: yes

#1337 Updated the citation version to the most receent flax version
  README.md
Labels: cla: yes, pull ready

#1329 Improve bash commands in LM1B README.md
  examples/lm1b/README.md
  examples/lm1b/input_pipeline.py
Labels: cla: yes, pull ready

#1332 Correct a small mistake in the documentation for `ScopeParamNotFoundError`
  flax/errors.py
Labels: cla: yes, pull ready

#1343 Fix atari dep
  setup.py
Labels: cla: yes, pull ready

#1342 Remove enable_omnistaging
  docs/notebooks/flax_basics.ipynb
Labels: cla: yes, pull ready

#1328 Make README and Module docstring examples runnable
  README.md
  flax/linen/module.py
Labels: cla: yes, pull ready
