Repository google/flax, pull requests merged in 2021-02, with the labels that each got.

#952 Log info message when a checkpoint is not found in the directory.
  flax/training/checkpoints.py
Labels: cla: yes, pull ready

#939 Improves documentation in various places
  README.md
  docs/notebooks/flax_basics.ipynb
  flax/linen/module.py
  flax/optim/base.py
  flax/training/common_utils.py
Labels: cla: yes, pull ready

#733 Document the `flax.optim` Adam optimizer
  flax/optim/adam.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#960 Update README to describe community involvement
  README.md
Labels: cla: yes, pull ready

#700 Add Adadelta Optimizer
  flax/optim/__init__.py
  flax/optim/adadelta.py
  tests/optim_test.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#965 Fix dtype handling for Adam and LAMB optimizers in 64bit mode.
  flax/optim/adam.py
  flax/optim/lamb.py
Labels: Priority: P1 - high, cla: yes, pull ready

#973 Minor doc fix for ConvTranspose
  docs/flax.linen.rst
  flax/linen/linear.py
Labels: cla: yes, pull ready

#981 Adds vscode settings to gitignore
  .gitignore
Labels: cla: yes

#990 Adds CSS for displaying codediff tables correctly
  docs/_static/css/flax_theme.css
Labels: cla: yes

#985 Adds ensembling HOWTO
  docs/_ext/codediff.py
  docs/howtos/ensembling.rst
Labels: cla: yes

#980 Learning rate schedule how-to
  docs/howtos/lr_schedule.rst
Labels: cla: yes

#1002 Set order of HOWTOs explicitly on left readthedocs navbar
  docs/index.rst
Labels: cla: yes

#683 Add call override for use_running_average
  CHANGELOG.md
  docs/design_notes/arguments.md
  examples/pixelcnn/model_test.py
  examples/pixelcnn/pixelcnn.py
  examples/pixelcnn/train.py
  flax/linen/attention.py
  flax/linen/module.py
  flax/linen/normalization.py
  flax/linen/stochastic.py
  tests/linen/linen_attention_test.py
  tests/linen/linen_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1020 Fix init/apply return annotation
  flax/core/scope.py
  flax/linen/module.py
Labels: cla: yes, pull ready

#1021 Link from Linen README to the reference docs
  flax/linen/README.md
Labels: cla: yes, pull ready

#976 Generalize attribute assignment to support passing module instances
  flax/core/lift.py
  flax/linen/linear.py
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1023 Fix incorrect attribute wrapping
  flax/linen/module.py
  tests/linen/module_test.py
Labels: cla: yes, pull ready

#1024 Add axis_name arg to lifted vmap
  flax/core/lift.py
  tests/linen/linen_transforms_test.py
Labels: cla: yes, pull ready

#1001 Deprecation
  flax/nn/.vscode/settings.json
  flax/nn/__init__.py
  flax/nn/attention.py
  flax/nn/base.py
  flax/nn/linear.py
  flax/nn/normalization.py
  flax/nn/pooling.py
  flax/nn/recurrent.py
  flax/nn/stochastic.py
  flax/nn/utils.py
Labels: cla: yes, pull ready

#913 Keep the behavior consistent when mutable is an empty dictionary
  CHANGELOG.md
  flax/core/scope.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1027 Convert all onp references to np
  examples/pixelcnn/model_test.py
  examples/pixelcnn/pixelcnn.py
  examples/pixelcnn/sample.py
  examples/ppo/agent.py
  examples/ppo/env_utils.py
  examples/ppo/models.py
  examples/ppo/ppo_lib.py
  examples/ppo/ppo_lib_test.py
  examples/ppo/test_episodes.py
  flax/core/flax_functional_engine.ipynb
  flax/core/nn/attention.py
  flax/core/nn/linear.py
  flax/jax_utils.py
  flax/linen/pooling.py
  flax/metrics/tensorboard.py
  flax/nn/attention.py
  flax/nn/linear.py
  flax/nn/pooling.py
  flax/optim/adafactor.py
  flax/optim/adagrad.py
  flax/optim/adam.py
  flax/optim/dynamic_scale.py
  flax/optim/lamb.py
  flax/optim/lars.py
  flax/optim/momentum.py
  flax/optim/rmsprop.py
  flax/optim/sgd.py
  flax/optim/weight_norm.py
  flax/training/common_utils.py
  flax/training/lr_schedule.py
  howtos/diffs/ensembling.diff
  tests/linen/toplevel_test.py
  tests/nn_attention_test.py
  tests/nn_linear_test.py
  tests/nn_test.py
  tests/optim_test.py
  tests/tensorboard_test.py
Labels: cla: yes, pull ready

#845 Add is_mutable method to Variable
  CHANGELOG.md
  flax/core/scope.py
  flax/linen/module.py
  tests/core/scope_test.py
  tests/linen/module_test.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1031 Do not enforce collections passed to apply to be frozen
  flax/core/scope.py
Labels: cla: yes, pull ready

#1042 Run doctests on GitHub actions
  .github/workflows/build.yml
Labels: cla: yes

#1040 Updated Module docstring
  flax/linen/module.py
Labels: Priority: P2 - medium, cla: yes, pull ready

#1043 Add functionality for capturing intermediates
  CHANGELOG.md
  docs/howtos/extracting_intermediates.rst
  docs/index.rst
  flax/linen/module.py
  tests/linen/module_test.py
Labels: Priority: P1 - high, cla: yes, pull ready

#1046 Release v0.3.1
  CHANGELOG.md
  flax/version.py
Labels: cla: yes
