Repository google/flax, pull requests merged in 2022-10, with the labels that each got.

#2495 Adoption cache should use WeakValueDictionary.
  flax/linen/module.py
Labels: pull ready

#2435 FLIP: General metadata
  docs/flip/2434-general-metadata.md
Labels: pull ready

#2499 Don't create reference cycles among Modules.
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#2511 adds perturb to docs
  docs/api_reference/flax.linen.rst
Labels: pull ready

#2515 Add extracting gradients section to capture intermediates guide
  docs/guides/extracting_intermediates.rst
Labels: Priority: P1 - soon, pull ready

#2496 Adds CallSetupUnboundModuleError
  flax/errors.py
  flax/linen/module.py
Labels: pull ready

#2492 Adding documentation to Dropout around rng use
  flax/linen/stochastic.py
Labels: pull ready

#2505 no-op when double wrapping with struct.dataclass
  flax/struct.py
  tests/struct_test.py
Labels: pull ready

#2517 Add epub and pdf RDT formats
  .readthedocs.yml
  flax/linen/stochastic.py
  flax/struct.py
  tests/struct_test.py
Labels: pull ready

#2366 Update landing page example
  docs/index.rst
Labels: Priority: P2 - eventual, pull ready

#2520 Add Tensorstore back to required dependencies.
  setup.py
Labels: pull ready

#2522 Delete flax.optim.rst
  docs/api_reference/flax.optim.rst
Labels: pull ready

#2529 Added an error for when we call init, init_with_output and apply on Module class.
  flax/errors.py
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#2521 Adding link to Bayesian Inference example that uses Flax
  docs/examples.rst
Labels: pull ready

#2486 Fix to use `is_initializing` for init-detection.
  flax/linen/normalization.py
Labels: pull ready

#2540 add rng_collection argument to Dropout
  flax/linen/stochastic.py
Labels: pull ready

#2507 Cancel tests if other jobs fail
  .github/workflows/build.yml
Labels: pull ready

#2544 Update Guides link in Flax README
  README.md
Labels: pull ready

#2545 Pin jupytext version in requirements.txt
  docs/requirements.txt
Labels: pull ready

#2510 Fix flax.linen.stochastic.Dropout
  .pre-commit-config.yaml
  flax/linen/stochastic.py
Labels: pull ready

#2394 Transfer Learning Guide
  docs/guides/index.rst
  docs/guides/transfer_learning.ipynb
  docs/guides/transfer_learning.md
  docs/requirements.txt
Labels: Priority: P2 - eventual, pull ready

#2546 Update Flax Contributing.md
  docs/advanced_topics/contributing.md
Labels: pull ready

#2553 cap dynamic scale to float32 max
  flax/training/dynamic_scale.py
Labels: pull ready

#2487 Update examples.rst with denoising-diffusion-flax
  docs/examples.rst
Labels: pull ready

#2548 return None if no _parent_ref is set
  flax/linen/module.py
Labels: pull ready

#2530 Add a documentation page on checkpointing
  .pre-commit-config.yaml
  docs/guides/index.rst
  docs/guides/use_checkpointing.ipynb
  docs/guides/use_checkpointing.md
Labels: pull ready

#2560 Lint Flax Contributing guide
  docs/advanced_topics/contributing.md
Labels: pull ready

#2559 Remove extra metadata in Checkpointing guide
  docs/guides/use_checkpointing.ipynb
  docs/guides/use_checkpointing.md
Labels: pull ready

#2563 Update getting_started.ipynb and getting_started.md
  docs/getting_started.ipynb
  docs/getting_started.md
Labels: pull ready
