Repository google/flax, pull requests merged in 2022-03, with the labels that each got.

#1949 Lifted while loop
  docs/flax.linen.rst
  flax/core/__init__.py
  flax/core/lift.py
  flax/linen/__init__.py
  flax/linen/transforms.py
  tests/core/core_lift_test.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#1954 Adds types and docstrings to seq2seq example
  examples/seq2seq/input_pipeline.py
  examples/seq2seq/models.py
  examples/seq2seq/train.py
Labels: pull ready

#1959 Automatically split decoder rng using nn.scan API in seq2seq example
  examples/seq2seq/README.md
  examples/seq2seq/models.py
Labels: pull ready

#1960 Fix type for user-facing precision arguments.
  examples/linen_design_test/attention_simple.py
  flax/linen/attention.py
  flax/linen/experimental/layers_with_named_axes.py
  flax/linen/linear.py
  flax/linen/recurrent.py
Labels: pull ready

#1922 Adds Linen upgrade guide
  docs/howtos/linen_upgrade_guide.rst
  docs/index.rst
Labels: pull ready

#1734 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: pull ready

#1955 Define Sequential module.
  CHANGELOG.md
  docs/flax.linen.rst
  flax/linen/__init__.py
  flax/linen/combinators.py
  tests/linen/linen_combinators_test.py
Labels: pull ready

#1919 improve jax pytree error messages with flax struct
  flax/struct.py
  tests/struct_test.py
Labels: pull ready

#1965 Fix typo in doc string
  flax/core/scope.py
Labels: pull ready

#1970 Fix example in nn.while_loop docstring
  flax/linen/transforms.py
Labels: pull ready

#1974 Expose has_rng as method on Modules.
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#1971 Add flax error for invalid transform target
  flax/errors.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#1984 Adds ipython_genutils to doc requirements
  docs/requirements.txt
Labels: pull ready

#1240 Add "max 5 commits in PR" to GH actions
  .github/workflows/build.yml
  docs/contributing.md
Labels: cla: yes, Priority: P2 - medium, pull ready

#1994 Update GroupNorm error msg to account for default value of num_groups
  flax/linen/normalization.py
Labels: pull ready

#1995 Add docstring to SelfAttention module, specifying call args.
  flax/linen/attention.py
Labels: pull ready

#1996 Fix typo in errors.py
  flax/errors.py
Labels: pull ready

#2001 Fix remaining setup aliasing conflict edgecase.
  flax/linen/module.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#2007 Enable support for non-string keys in state dicts.
  flax/serialization.py
  tests/linen/linen_module_test.py
Labels: pull ready

#1978 Include activations in Sequential example.
  flax/linen/combinators.py
Labels: pull ready

#2010 Bumps version to 0.4.1
  CHANGELOG.md
  README.md
  flax/version.py
Labels: pull ready

#2012 Bumps flax/jax versions in examples/imagenet.
  examples/imagenet/requirements.txt
Labels: pull ready

#2009 Canonicalize conv padding
  flax/linen/linear.py
  tests/linen/linen_linear_test.py
Labels: pull ready

#2013 Update ScopeParamNotFoundError message.
  flax/errors.py
  flax/linen/linear.py
  tests/core/core_lift_test.py
  tests/core/core_scope_test.py
Labels: pull ready

#1927 Set field on dataclass transform decorator
  flax/linen/module.py
  flax/struct.py
  setup.py
Labels: Status: blocked, pull ready

#2018 Don't recommend mixing setup and compact in docs.
  docs/design_notes/setup_or_nncompact.rst
Labels: pull ready

#2015 Update linear regression example in Jax intro and Flax intro.
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/jax_for_the_impatient.ipynb
Labels: pull ready

#2020 Lifted cond
  CHANGELOG.md
  docs/flax.linen.rst
  flax/core/lift.py
  flax/core/scope.py
  flax/linen/__init__.py
  flax/linen/module.py
  flax/linen/transforms.py
  tests/core/core_lift_test.py
  tests/core/core_scope_test.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#1990 PEP484-compatible export of names in flax & its public modules
  flax/__init__.py
  flax/core/__init__.py
  flax/core/nn/__init__.py
  flax/linen/__init__.py
Labels: pull ready
