Repository google/flax, pull requests merged in 2022-07, with the labels that each got.

#2234 Add a method for detecting the use of "init" functions.
  docs/flax.linen.rst
  flax/core/lift.py
  flax/core/scope.py
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#2258 Small fix in MNIST example
  examples/mnist/train.py
Labels: pull ready

#2269 Fix typos in the doc of `flax.linen.Module.bind`
  flax/linen/module.py
Labels: pull ready

#2276 Add colab button to flax_basics
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/flax_basics.md
  docs/notebooks/jax_for_the_impatient.ipynb
  docs/notebooks/jax_for_the_impatient.md
  docs/notebooks/linen_intro.ipynb
  docs/notebooks/linen_intro.md
Labels: pull ready

#2281 Fix type annotations
  flax/linen/attention.py
  flax/linen/module.py
  flax/linen/recurrent.py
  tests/linen/linen_module_test.py
Labels: pull ready

#2199 Exclude pseudo-fields of dataclass
  flax/struct.py
Labels: pull ready

#2296 Fix variable aliasing in put_variable
  flax/core/scope.py
  tests/core/core_lift_test.py
  tests/core/core_scope_test.py
Labels: Priority: P0 (urgent), pull ready

#2330 0.5.3 update version & changelog
  CHANGELOG.md
  README.md
  flax/version.py
Labels: pull ready

#2313 Replace use of id() with global counter-based id.
  flax/core/scope.py
  flax/ids.py
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/linen_test.py
Labels: pull ready

#2177 RDT Redesign
  .gitignore
  docs/_static/css/flax_theme.css
  docs/advanced_topics/arguments.md
  docs/advanced_topics/contributing.md
  docs/advanced_topics/convert_pytorch_to_flax.rst
  docs/advanced_topics/index.rst
  docs/advanced_topics/lift.md
  docs/advanced_topics/linen_design_principles.rst
  docs/advanced_topics/linen_upgrade_guide.rst
  docs/advanced_topics/module_lifecycle.rst
  docs/advanced_topics/optax_update_guide.rst
  docs/advanced_topics/philosophy.md
  docs/api_reference/flax.config.rst
  docs/api_reference/flax.core.frozen_dict.rst
  docs/api_reference/flax.errors.rst
  docs/api_reference/flax.jax_utils.rst
  docs/api_reference/flax.linen.rst
  docs/api_reference/flax.optim.rst
  docs/api_reference/flax.serialization.rst
  docs/api_reference/flax.struct.rst
  docs/api_reference/flax.traceback_util.rst
  docs/api_reference/flax.training.rst
  docs/api_reference/flax.traverse_util.rst
  docs/api_reference/index.rst
  docs/conf.py
  docs/examples.rst
  docs/getting_started.ipynb
  docs/getting_started.md
  docs/guides/ensembling.rst
  docs/guides/extracting_intermediates.rst
  docs/guides/flax_basics.ipynb
  docs/guides/flax_basics.md
  docs/guides/full_eval.rst
  docs/guides/index.rst
  docs/guides/jax_for_the_impatient.ipynb
  docs/guides/jax_for_the_impatient.md
  docs/guides/lr_schedule.rst
  docs/guides/model_surgery.rst
  docs/guides/setup_or_nncompact.rst
  docs/guides/state_params.rst
  docs/index.rst
Labels: Priority: P2 - eventual, pull ready

#2338 Fix stale URLs to read the docs site.
  flax/errors.py
  flax/jax_utils.py
  flax/linen/README.md
  flax/linen/recurrent.py
  flax/optim/README.md
  flax/optim/base.py
  flax/traverse_util.py
Labels: pull ready

#2339 Forward unroll argument in scan_with_axes
  flax/linen/partitioning.py
Labels: pull ready

#2317 Document repo analytics
  .github/analytics/README.md
  .github/analytics/get_repo_metrics.py
  .github/analytics/requirements.txt
  setup.py
Labels: Priority: P1 - soon, pull ready

#2291 Improve flax basics
  docs/guides/flax_basics.ipynb
  docs/guides/flax_basics.md
Labels: Priority: P2 - eventual, pull ready

#2277 Split build into multiple jobs
  .github/workflows/build.yml
  tests/run_all_tests.sh
Labels: Priority: P1 - soon, pull ready

#2343 Fix type annotation for `step` in `training.checkpoints`
  flax/training/checkpoints.py
Labels: pull ready
