Repository google/flax, pull requests merged in 2022-05, with the labels that each got.

#2099 Fix error from jax test util warning.
  pytest.ini
Labels: pull ready

#2098 [remove-units] partial_eval_jaxpr -> partial_eval_jaxpr_nounits
  flax/core/axes_scan.py
Labels: pull ready

#2103 Bumps Flax to v0.4.2 and adds CHANGELOG notes
  CHANGELOG.md
  README.md
  flax/version.py
Labels: pull ready

#2075 Removes deprecated HOWTOs
  docs/deprecated_howtos/checkpointing.rst
  docs/deprecated_howtos/distributed-training.rst
  docs/deprecated_howtos/ensembling.rst
  docs/deprecated_howtos/howtos-howto.md
  docs/deprecated_howtos/index.rst
  docs/deprecated_howtos/polyak-averaging.rst
  docs/deprecated_howtos/scheduled-sampling.rst
Labels: pull ready

#2090 Improves early stopping docstring
  docs/flax.training.rst
  flax/training/early_stopping.py
Labels: pull ready

#2088 Linen activations import
  flax/linen/__init__.py
  flax/linen/activation.py
Labels: Priority: P1 - soon, pull ready

#2129 Update link to JAX installation page
  docs/installation.md
Labels: pull ready

#2111 Adds "full eval" HOWTO.
  CHANGELOG.md
  docs/flax.jax_utils.rst
  docs/howtos/full_eval.rst
  docs/index.rst
  docs/notebooks/full_eval.ipynb
  flax/jax_utils.py
  tests/jax_utils_test.py
Labels: Priority: P1 - soon, pull ready

#2113 Repo Analytics
  .github/analytics/get_repo_metrics.py
  .github/analytics/issue_activity_since_date.gql
  .github/analytics/pr_data_query.gql
  setup.py
Labels: Priority: P2 - eventual, pull ready

#2058 Implement default dtype FLIP
  CHANGELOG.md
  docs/flip/1777-default-dtype.md
  flax/linen/activation.py
  flax/linen/attention.py
  flax/linen/dtypes.py
  flax/linen/linear.py
  flax/linen/normalization.py
  flax/linen/recurrent.py
  tests/linen/linen_activation_test.py
  tests/linen/linen_attention_test.py
  tests/linen/linen_dtypes_test.py
  tests/linen/linen_linear_test.py
  tests/linen/linen_module_test.py
  tests/linen/linen_test.py
Labels: Priority: P1 - soon, pull ready

#2138 Adds flax import to summary.py
  flax/linen/summary.py
Labels: pull ready

#1801 Update download_dataset_metadata.sh
  tests/download_dataset_metadata.sh
Labels: Priority: P2 - eventual, pull ready

#2136 Mark correct minimum jax version requirement
  setup.py
Labels: pull ready

#2151 Edited contributing.md
  contributing.md
Labels: pull ready

#2106 Add typehint to Module.scope
  flax/linen/module.py
Labels: Priority: P1 - soon, pull ready

#2140 Correcting Mistakes In Flip Docs
  docs/flip/1777-default-dtype.md
Labels: pull ready

#2154 Calculate cumulative number or issues and prs
  .github/analytics/get_repo_metrics.py
Labels: pull ready

#2155 Improve setup instructions in contributing guide
  docs/contributing.md
Labels: Priority: P1 - soon, pull ready

#2158 Forward unroll argument in lifted scan
  flax/core/axes_scan.py
  flax/core/lift.py
  flax/linen/transforms.py
Labels: pull ready
