Repository google/flax, pull requests merged in 2022-06, with the labels that each got.

#2162 Improve tabulate
  flax/linen/module.py
  flax/linen/summary.py
  tests/linen/summary_test.py
Labels: Priority: P1 - soon, pull ready

#2172 Allow nn.cond, nn.while to act on bound methods.
  flax/linen/module.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#2180 0.5.1
  CHANGELOG.md
  README.md
  flax/version.py
Labels: pull ready

#2181 Flax Basics docs: Add missing `@jax.jit` to `mse`
  docs/notebooks/flax_basics.ipynb
Labels: pull ready

#2188 add missing colon in example code
  docs/design_notes/lift.md
Labels: pull ready

#2193 Add missing PyYAML dependency
  .github/workflows/build.yml
  setup.py
Labels: Priority: P0 (urgent), pull ready

#2167 Improve module docs
  docs/_templates/autosummary/flax_module.rst
  docs/conf.py
  docs/conf_sphinx_patch.py
Labels: Priority: P1 - soon, pull ready

#1916 Changed optimizer to optax
  examples/nlp_seq/README.md
  examples/nlp_seq/train.py
Labels: Priority: P1 - soon, pull ready

#2206 Show repository button
  docs/conf.py
Labels: pull ready

#2203 v0.5.2
  CHANGELOG.md
  README.md
  flax/version.py
Labels: pull ready

#2213 Fix missing passthrough of nn.scan unroll arg
  flax/linen/transforms.py
Labels: pull ready

#2166 Test Notebooks on CI
  .github/workflows/build.yml
  docs/conf.py
  docs/contributing.md
  docs/notebooks/annotated_mnist.ipynb
  docs/notebooks/annotated_mnist.md
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/flax_basics.md
  docs/notebooks/full_eval.ipynb
  docs/notebooks/full_eval.md
  docs/notebooks/jax_for_the_impatient.ipynb
  docs/notebooks/jax_for_the_impatient.md
  docs/notebooks/linen_intro.ipynb
  docs/notebooks/linen_intro.md
  docs/notebooks/optax_update_guide.ipynb
  docs/notebooks/optax_update_guide.md
  docs/notebooks/state_params.ipynb
  docs/notebooks/state_params.md
  docs/requirements.txt
Labels: Priority: P1 - soon, pull ready

#2228 Bump numpy from 1.21.4 to 1.22.0 in examples
  examples/imagenet/requirements.txt
  examples/lm1b/requirements.txt
  examples/mnist/requirements.txt
  examples/nlp_seq/requirements.txt
  examples/ogbg_molpcba/requirements.txt
  examples/ppo/requirements.txt
  examples/seq2seq/requirements.txt
  examples/sst2/requirements.txt
  examples/vae/requirements.txt
  examples/wmt/requirements.txt
Labels: pull ready

#2205 Add nn.switch
  docs/flax.linen.rst
  flax/core/lift.py
  flax/linen/__init__.py
  flax/linen/transforms.py
  tests/core/core_lift_test.py
  tests/linen/linen_transforms_test.py
Labels: pull ready

#2231 Fix notebooks
  docs/conf.py
  docs/notebooks/flax_basics.ipynb
  docs/notebooks/jax_for_the_impatient.ipynb
  docs/notebooks/jax_for_the_impatient.md
  docs/notebooks/linen_intro.ipynb
  docs/notebooks/linen_intro.md
  docs/notebooks/state_params.ipynb
  docs/notebooks/state_params.md
  docs/requirements.txt
Labels: pull ready

#2235 Add launch section with colab button
  docs/conf.py
Labels: pull ready

#2238 Enabling the dollarmath extension of MyST to render correctly math expresions
  docs/conf.py
Labels: pull ready

#2253 Fix tests
  docs/howtos/convert_pytorch_to_flax.rst
  tests/traceback_util_test.py
Labels: pull ready

#2233 Add single-host async save to save_checkpoint.
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: pull ready
