Repository google/flax, pull requests merged in 2022-09, with the labels that each got.

#2427 PIL does not accept DeviceArray, so needed to use numpy.
  examples/vae/utils.py
Labels: pull ready

#2367 Move examples to RTD
  docs/examples.rst
  examples/README.md
Labels: Priority: P1 - soon, pull ready

#2388 Simplify dynamic context
  flax/linen/module.py
Labels: Priority: P2 - eventual, pull ready

#2446 Remove pytype generic workaround
  flax/core/lift.py
Labels: pull ready

#2457 Add static_argnums to nn.checkpoint
  flax/core/lift.py
  flax/linen/transforms.py
  tests/linen/linen_transforms_test.py
Labels: Priority: P1 - soon, pull ready

#2473 Fix Managing Parameters and State docs
  docs/guides/state_params.rst
Labels: pull ready

#2470 Use gfile.listdir instead of gfile.glob in checkpointing
  flax/training/checkpoints.py
  tests/checkpoints_test.py
Labels: pull ready

#2458 Create test matrix to speedup tests
  .github/workflows/build.yml
  tests/run_all_tests.sh
Labels: pull ready

#2425 Fix Conv docstrings
  flax/linen/linear.py
Labels: Priority: P2 - eventual, pull ready

#2465 Use proper scikit-learn dependency
  docs/requirements.txt
Labels: pull ready

#2451 Adding "count_include_pad" argument to flax.linen.pooling.avg_pool
  flax/linen/pooling.py
  tests/linen/linen_test.py
Labels: pull ready

#2476 Add perturb() to allow capturing intermediate gradients
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#2491 fix DynamicScale docstring
  flax/training/dynamic_scale.py
Labels: pull ready

#2490 test against python 3.8 and 3.9
  .github/workflows/build.yml
  examples/ogbg_molpcba/train.py
  examples/ogbg_molpcba/train_test.py
Labels: Priority: P1 - soon, pull ready

#2494 Update version to 0.6.1
  CHANGELOG.md
  flax/version.py
Labels: pull ready
