Repository google/flax, pull requests merged in 2023-09, with the labels that each got.

#2585 Add RNN FLIP
  docs/flip/2396-rnn.md
Labels: Priority: P1 - soon, pull ready

#3308 Minor fix to jax_utils.prefect_to_device
  flax/jax_utils.py
Labels: pull ready

#3317 add tf-text to doc requirements
  docs/requirements.txt
Labels: pull ready

#3281 Allow apply's method argument to accept submodules
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#3314 Update handling of typed PRNG keys
  flax/core/scope.py
Labels: pull ready

#3326 0.7.3 release
  CHANGELOG.md
  README.md
Labels: pull ready

#3331 Update minimum python version info.
  examples/lm1b/input_pipeline.py
  examples/ppo/ppo_lib.py
  examples/wmt/input_pipeline.py
  pyproject.toml
  tests/linen/linen_module_test.py
Labels: pull ready

#3334 0.7.5
  README.md
  flax/version.py
Labels: pull ready

#3277 Add method-to-model section to Haiku migration guide
  docs/guides/haiku_migration_guide.rst
Labels: Priority: P2 - eventual, pull ready

#3343 updated haiku guide with new JAX RNG api
  docs/guides/haiku_migration_guide.rst
Labels: pull ready

#3344 changed resnet v1 to v1.5
  examples/imagenet/models.py
  examples/imagenet/models_test.py
Labels: pull ready

#3342 updated flax_basics
  docs/guides/flax_basics.ipynb
  docs/guides/flax_basics.md
Labels: pull ready

#3306 Add `find` methods and magic methods for Cursor API
  docs/api_reference/flax.cursor.rst
  flax/cursor.py
  flax/errors.py
  tests/cursor_test.py
Labels: pull ready

#3352 fix DeprecationWarnings
  docs/conf.py
  flax/core/axes_scan.py
  flax/core/partial_eval.py
  flax/jax_utils.py
  pyproject.toml
Labels: pull ready

#3358 Make checkpoint guide path absolute
  docs/guides/orbax_upgrade_guide.rst
  docs/guides/use_checkpointing.ipynb
  docs/guides/use_checkpointing.md
  docs/notebooks/orbax_upgrade_guide.ipynb
  docs/notebooks/orbax_upgrade_guide.md
Labels: pull ready

#3354 use jax.Array type for rng keys
  docs/guides/dropout.rst
  examples/seq2seq/models.py
  flax/linen/module.py
  flax/linen/recurrent.py
  flax/linen/stochastic.py
Labels: pull ready

#3356 Disable pyink
  .pre-commit-config.yaml
  pyproject.toml
Labels: pull ready

#3359 removed DeprecationWarning filter
  pyproject.toml
Labels: pull ready

#3357 Don't propagate default args in Tabulate
  flax/linen/module.py
  flax/linen/summary.py
  tests/linen/summary_test.py
Labels: pull ready

#3335 added spectral norm
  docs/api_reference/flax.linen/layers.rst
  flax/linen/__init__.py
  flax/linen/normalization.py
  tests/linen/linen_test.py
Labels: pull ready

#3365 fixed bind-unbind bug
  flax/core/scope.py
  flax/linen/module.py
  tests/linen/linen_module_test.py
Labels: pull ready

#3368 Add MaxText open source LLM to index.rst
  docs/index.rst
Labels: pull ready

#3367 fixed typo
  docs/api_reference/flax.errors.rst
Labels: pull ready

#3322 Add fp8 custom op and unit test
  flax/linen/__init__.py
  flax/linen/fp8_ops.py
  flax/training/train_state.py
  tests/linen/linen_linear_test.py
Labels: pull ready

#3371 fixed scope typing
  flax/linen/module.py
Labels: pull ready

#3373 Trailing whitespace fixes.
  flax/linen/fp8_ops.py
  flax/training/train_state.py
  tests/linen/linen_linear_test.py
Labels: pull ready

#3374 Make fp8 ops use explicit broadcasting.
  flax/linen/fp8_ops.py
Labels: pull ready
